### ISSUE TITLE
Default OS clarity

### ISSUE THREAD

**Issue by landNull** [omega8cc/boa#1788] opened 2024-04-29 22:01 UTC
Hi,

Thank you all for your hard work on BOA.

I need some clarity on the OS to use for the initial install.

In the <>Code github README.txt it says

"
@=> SUPPORTED OPERATING SYSTEMS -- please read also: docs/CAVEATS.txt

  Devuan @ https://www.devuan.org/os/releases

  * Devuan Chimaera (fully supported and the only OS version recommended)
 "

In the docs/INSTALL.txt it says

"
* Since Debian is running systemd, it should be removed before installing BOA,
  which involves procedure in five steps, as outlined further below.

&

4. Remove systemd in five steps:

   S1. Run 'boa init' command -- it will install sysvinit.
   S2. Reboot the server.
   S3. Run 'boa init' again so it can remove systemd.
   S4. Reboot the server again.
   S5. Run boa standard install command, as outlined below.
"

I'm installing on a VPS that can only provide Debian installs. 
So I had them do a fresh install of Debian Bullseye.

Q: Do I migrate the clean Bullseye to Devuan then run install
OR
Do I just follow the 5 steps in Step 4 and it is all good to go?

**Comment by omega8cc** [comment] 2024-04-29 22:29
Good question. BOA requires that you first install it using the multi-step procedure on Debian. Only then you can upgrade it to Devuan, or just stay on Debian, although it’s not recommended.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment] 2024-04-29 23:35
We could perhaps add the procedure to upgrade Debian to Devuan before actually installing BOA. It would also make the migration to Devuan slightly faster.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by landNull** [comment] 2024-04-30 21:00
**My thoughts** (for what their worth)

*While the "Devuan first" install time is significantly less than the "Debian first" method, "Debian first" just works.
*In my opinion the best approach initially would be to edit the <>Code README.txt and the decs/INSTALL.txt to state the "Debian" first method upfront.

**EX:** BOA must to be installed on Debian Bullseye with systemd replaced by sysvinit before migrating to Devuan Chimera refer to the step 4 in docs/INSTALL.txt
      
*Additionally you could have the script detect the OS version and use modified scripts to provide the same experience as the "Debian first" method. 

Due to time constraints and deadlines I have opted for the "Debian first" method. In the end I hope this was a helpful exercise and leads to time savings for everyone in the future.

**Thank you all again for all of your hard work!** 
  
Here are all of the steps I took with each ERROR I experienced along with the SOLUTION I used.

*Fresh install of Debian Bullseye on VPS
*Login using password provided by host
*Change password
*Command passwd
*Create passwordless rsa key
**Add rsa key to root
*Edit or create .ssh/config
**nano .ssh/config
**Add alias to zsh
*Migrate Debian to Devuan using instructions from https://www.devuan.org/os/documentation/install-guides/chimaera/bullseye-to-chimaera
*Login to root
*command cd;rm -f BOA*
*command wget -q -U iCab http://files.aegir.cc/BOA.sh.txt
*command bash BOA.sh.txt
*I skipped boa init as systemd is not installed (I acknowledge this may have led to some of the ERRORS I received.)
*command screen 

**ERROR!** 

> -bash: screen: command not found

**SOLUTION**

> Apt install screen

*command screen
*Screen dialog loads
*Press spacebar
* command boa in-lite localhost my@email o1 none php-min

**ERROR:** (Host installs Apapch2 by default)

> BOA requires minimal supported OS with no services installed.

> Please make sure you don't have MySQL nor Apache installed.
> Here's the list of directories which shouldn't exist:
> /etc/nginx /etc/apache2 /etc/mysql /var/lib/mysql /var/aegir

> HINT: Try to run: apt-get purge mysql-common --and then try again.
> HINT: You can also enforce installation with empty control file:
>  touch /root/.force.reinstall.cnf -- and then try again.

> Bye

Solution

> apt remove --purge apache2
> rm -rf /etc/nginx /etc/apache2 /etc/mysql /var/lib/mysql /var/aegir(just in case)

* command boa in-lite public server.mydomain.org my@email o1 none php-min

*Install runs for some time

**ERROR!**

> Displaying the last 15 lines of logfile
>   /var/backups/barracuda-install-240429-232517.log
> to help troubleshoot this problem

> If you see any error with advice to run 'dpkg --configure --force-all -a'
> run this command with default answer, then run this installer again
 
> Need to get 49.6 kB of archives.
> After this operation, 118 kB of additional disk space will be used.
> Get:1 http://deb.devuan.org/merged chimaera/main amd64 tree amd64 1.8.0-1+b1 [49.6 kB]
> Fetched 49.6 kB in 1s (65.0 kB/s)
> Selecting previously unselected package tree.
> (Reading database ... 72117 files and directories currently installed.)
> Preparing to unpack .../tree_1.8.0-1+b1_amd64.deb ...
> Unpacking tree (1.8.0-1+b1) ...
> Setting up javascript-common (11+nmu1) ...
> dpkg: error processing package javascript-common (--configure):
>  installed javascript-common package post-installation script subprocess returned error exit status 1


*Install completed

**ERROR!**

> master.domain.name/firstTimeUseLinkURL not loading

> csf has blocked me

SOLUTION

> Had hosting provider disable csf

**ERROR!**

> reload onetime login link page greeted with the page your loading is insecure


**SOLUTION**

> Accept risks load anyway 

**ERROR!**

> onetime link fails with already used notice

> tried resetting the password postfix failed to send email 

> Could not ssh using the custom port number

**SOLUTION**

> `Tried default Port 22

> ssh root@domain.name worked

*su -s /bin/bash aegir
*tried regenerating uli
*drush @hostmaster uli 1
*tried using freshly generated link 

**ERROR!**

> failed with link already used

**SOLUTION**

> reset password via drush

> drush @hostmaster upwd --password=yourpassword 1


*click login tab
*enter new password
*Success

**ERROR!**

> https not working

**SOLUTION**

> accept the risks

**ERROR!**

> master.domain.name not verified

**ERROR!**

> nginx on sven.snrg.us could not be restarted. Changes might not be available until this has been done. (error: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
> nginx: configuration file /etc/nginx/nginx.conf test is successful
> Reloading (via HUP) Nginx Server...: failed!)

**ISSUE!**

> csf appears to have re-enabled 

> lost access to server only port 80 and 443 open

*Had hosting provider reinstall debian 11 bullseye going to install BOA via "Debian first" as per docs/INSTALL.txt

**Comment by omega8cc** [comment] 2024-04-30 22:20
Wow! Great illustration of all the hard work BOA is doing for you when used as intended. All the magic included is a result of countless hours of tedious testing, failing and debugging.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by landNull** [comment] 2024-04-30 22:42
> Wow! Great illustration of all the hard work BOA is doing for you when used as intended. All the magic included is a result of countless hours of tedious testing, failing and debugging.
> 
> Sent with [GitHawk](http://githawk.com)

No doubt! 
I have an opportunity to try the "Devuan first" including boa init this time I will report back with my final breakdown.

**Comment by landNull** [comment] 2024-05-01 02:12
### **First things first BOA is badass!!!**
"Devuan first" method worked...ish!!! ;) 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING
This is NOT a recommended install method
In the end I did this out of shear curiosity and 
in the hopes of providing some insight to the devs
in case they chose to provide a "Devuan first" install
at some point.  
ZERO SUPPORT GIVEN IF U DECIDE TO TRY THIS
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I was not expecting this outcome. 

I simply had another opportunity to test one last variation I had not tried yet on a "Devuan first" BOA install figuring I might dig up more info for devs and to satisfy my curiosity.  

**The Breakdown**

- Fresh install of Debian Bullseye on VPS
- Login using password provided by host
- Change password
- passwd
- Prep Work I did on my VPS
- sudo nano /etc/hostname
- delete hostname
- crtl x  
- y
- reboot
- ssh-copy-id -i ~/.ssh/id_rsa.pub root@ip.add.re.ss -p customPort# 
- ssh root@ip.add.re.ss -p custom port
- apt remove --purge apache2
- rm -rf /etc/nginx /etc/apache2 /etc/mysql 
- Migrate Debian to Devuan using instructions from https://www.devuan.org/os/documentation/install-guides/chimaera/bullseye-to-chimaera
- boa init

****ERROR!****

> BOA [18:01:24] ==> MODE: NORMAL INIT
> BOA [18:01:24] ==> FATAL ERROR: You must define also _EASY_HOSTNAME

> ATTEMPTED to troubleshoot via various iterations of the error 

> 1. Full error
> 2. Removed timestamp
> 3. No insight was gained.  

- reboot
- ssh root@ip.add.re.ss -p custom port
- screen
- boa in-lite public server.mydomain.org my@email o1 none php-min
- Installer runs 

**GLITCH**

> The script stopped outputting updates on the install to the terminal screen 
> Looking at the install log shows install stopped out put to the log after printing  
> 
> Waiting for MySQLD graceful shutdown...to the screen or logs
> MySQLD stopped
> Removing locks...
> MySQLD stop procedure completed
> Creating locks...
> Starting MySQLD again...
> Waiting for MySQLD graceful start...
> MySQLD started
> Removing locks...
> MySQLD start procedure completed

- After waiting for 30 minutes with no futher output 
- Tested to make sure the erver was still running 
- Viewd htop everything looked good
- su -s /bin/bash aegir 
- drush @hostmaster verify
- All good
- drush @hostmaster uli
- loaded uli in browser
- no ssl cert warning
- accept risks 
- Initial login page loads everything is working great
- apt update 
- To confirm I not halucinating 
 
**OUTPUT**

> Get:1 http://repo.percona.com/percona/apt bullseye InRelease [9899 B]
> Get:2 http://repo.percona.com/percona/apt bullseye/main Sources [4308 B]
> Get:3 http://repo.percona.com/percona/apt bullseye/main amd64 Packages [17.6 kB]
> Get:4 http://deb.devuan.org/merged chimaera InRelease [33.5 kB]
> Get:5 http://deb.devuan.org/merged chimaera-updates InRelease [26.1 kB]
> Get:6 http://deb.devuan.org/merged chimaera-security InRelease [26.4 kB]
> Get:7 http://deb.devuan.org/merged chimaera/main Sources [8604 kB]
> Get:8 http://deb.devuan.org/merged chimaera/main amd64 Packages [8312 kB]
> Get:9 http://deb.devuan.org/merged chimaera/main Translation-en [6479 kB]
> Get:10 http://deb.devuan.org/merged chimaera-updates/main Sources [8164 B]
> Get:11 http://deb.devuan.org/merged chimaera-updates/main amd64 Packages [17.9 kB]
> Get:12 http://deb.devuan.org/merged chimaera-updates/main Translation-en [11.2 kB]
> Get:13 http://deb.devuan.org/merged chimaera-security/main Sources [159 kB]
> Get:14 http://deb.devuan.org/merged chimaera-security/main amd64 Packages [276 kB]
> Get:15 http://deb.devuan.org/merged chimaera-security/main Translation-en [191 kB]

- I watching the install log throughout the whole install 
- tail -f /var/backups/barracuda-install-DATE-TIME.log
- No errors printed to the log, but the script stopped printing to the screen, and logs.

**CONCLUSION**

- No matter how you approach the install "Debian first" or "Devuan first" BOA installer is badass!!
- I did this mostly out of curiosity  
- Definitely not the result I expected
- I was not disconnected from the remote access at anytime during the install and the syslog show no errors  
- I wish it had printed all of the output to the log as I would have something more to offer the devs :(
- I hope my sucessflish ;) experiment is helpful in some way.

**Comment by omega8cc** [comment] 2024-05-01 20:28
It’s exciting to see you willing to experiment and share the results with others, how refreshing attitude, thank you!

**Comment by landNull** [comment] 2024-05-01 21:31
> It’s exciting to see you willing to experiment and share the results with others, how refreshing attitude, thank you!

You're very welcome! Right back at you! :smile:

**Comment by landNull** [comment] 2024-05-01 21:46
**UPDATE**
In the end the only error I experienced with the "Devuan first" install is after running boa init on a fresh Devuan migration.

> BOA [18:01:24] ==> MODE: NORMAL INIT
> BOA [18:01:24] ==> FATAL ERROR: You must define also _EASY_HOSTNAME

So in the end the only issue is the _EASY_HOSTNAME variable not populate on Devuan. I have no idea if this is a small thing to address or not.

This glitch with the script and install log not printing output after the database restart has nothing to do with the BOA script it is specific to a weird connection timeout issue I'm experiencing with my remote connection.  

I was able to confirm this after I processed a "Debian first" install as it stopped printing to the screen at the same exact point. 

Yet in a previous "Debian first" install (#LearningCurve) everything worked as advertised.

**Comment by jasonmce** [comment] 2024-07-05 15:10
**CONFIRMATION** 
I was also able to do a full clean install this way:

- Start with a vanilla Bullseye linode
- Migrate to Chimera using the instructions linked in "[Migrate Debian to Devuan using instructions](https://www.devuan.org/os/documentation/install-guides/chimaera/bullseye-to-chimaera)" above
- Skip the "boa init" steps since it is already free of systemd
- Jump straight to "boa in-lite public {fqdn} {email} {octopus-name} none php-min"

... and things seems to be running smoothly.

**Comment by omega8cc** [comment] 2024-07-05 16:18
It has been greatly improved and simplified in dev and will be released once all testing and debugging is complete. You will be able to start from any available Debian version and get to latest Devuan Daedalus with a one-word command.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment] 2024-08-30 19:27
Closing since it's now explained in the updated docs.

**Closed by omega8cc** 2024-08-30 19:27 UTC
Labels: type - feature request, status - needs work
