### ISSUE TITLE
? incorrect ffmpeg library - libavcodec-extra-53

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#907] opened 2016-04-12 09:06 UTC
It appears that barracuda 3.0.1 is trying to install a library version php 5.3 of a file which is missing (libavcodec-extra-53) when we are using only 5.6 - this is regarding ffmpeg: should we be installing libav-tools instead, as aptitude recommends?

copy of barracuda up-stable (3.0.1) here:
https://gist.github.com/EdNett/7f9761060fee97b66853b18c2d5b04ee

boa info more is here:
https://gist.github.com/EdNett/88f4d6e2a91d8b9e1aa1faaedc23912d

**Comment by omega8cc** [comment] 2016-04-12 13:41
This feature is not reliable at the moment. I'm marking this as duplicate of #883

**Closed by omega8cc** 2016-04-12 13:41 UTC
Labels: status - duplicate
