### ISSUE TITLE
curl: /usr/local/lib/libcurl.so.4: no version information available (required by curl)

### ISSUE THREAD

**Issue by fotiDim** [omega8cc/boa#1801] opened 2024-08-24 21:40 UTC
After updating to 5.4-lts / deadalus I keep getting `curl: /usr/local/lib/libcurl.so.4: no version information available (required by curl)` when logging in and also when running any update related command.

[boa info.txt](https://github.com/user-attachments/files/16740233/boa.info.txt)

**Comment by omega8cc** [comment] 2024-08-24 23:03
Please provide required report about your system -- `boa info`

**Comment by fotiDim** [comment] 2024-08-25 12:15
@omega8cc attached it to the first post.

**Comment by omega8cc** [comment] 2024-08-25 17:33
Please try to reinstall curl from packages using these commands:

```
echo "curl install" | dpkg --set-selections
apt-get update
apt-get install curl -y
apt-get build-dep curl -y
apt-get remove libssl1.0-dev -y --purge --auto-remove
apt-get autoremove -y
apt-get install libssl-dev -y
apt-get install libc-client2007e libc-client2007e-dev -y

```

**Comment by fotiDim** [comment] 2024-08-25 21:24
These commands didn't help. What solved it temporarily was:
```
sudo rm /usr/local/lib/libcurl.so.4
sudo ln -s /usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0 /usr/local/lib/libcurl.so.4
```
but after update the problem comes back.

**Comment by omega8cc** [comment] 2024-08-26 00:33
Your major OS upgrade didn't work as expected if you still have that old `libcurl` there.

Please attach more history with `boa info more`

Please also show us the results of:

`ll /usr/lib/x86_64-linux-gnu/libcurl*`

and

`ll /usr/local/lib/libcurl*`

**Comment by fotiDim** [comment] 2024-08-26 09:15
[boa info more ⬇️](https://github.com/user-attachments/files/16746708/boa.info.more.txt)
---
`ll /usr/lib/x86_64-linux-gnu/libcurl*`
```
lrwxrwxrwx 1 root root   19 Apr  3 01:02 /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.3 -> libcurl-gnutls.so.4
lrwxrwxrwx 1 root root   23 Apr  3 01:02 /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 -> libcurl-gnutls.so.4.8.0
-rw-r--r-- 1 root root 676K Apr  3 01:02 /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.8.0
-rw-r--r-- 1 root root 1.4M Apr  3 01:02 /usr/lib/x86_64-linux-gnu/libcurl.a
lrwxrwxrwx 1 root root   16 Apr  3 01:02 /usr/lib/x86
---
_64-linux-gnu/libcurl.so -> libcurl.so.4.8.0
lrwxrwxrwx 1 root root   16 Apr  3 01:02 /usr/lib/x86_64-linux-gnu/libcurl.so.4 -> libcurl.so.4.8.0
-rw-r--r-- 1 root root 696K Apr  3 01:02 /usr/lib/x86_64-linux-gnu/libcurl.so.4.8.0
```

`ll /usr/local/lib/libcurl*`
```
-rw-r--r-- 1 root staff 1.4M Dec 27  2023 /usr/local/lib/libcurl.a
-rwxr-xr-x 1 root staff 1.1K Dec 27  2023 /usr/local/lib/libcurl.la*
lrwxrwxrwx 1 root staff   16 Dec 27  2023 /usr/local/lib/libcurl.so -> libcurl.so.4.8.0*
lrwxrwxrwx 1 root staff   42 Aug 25 23:23 /usr/local/lib/libcurl.so.4 -> /usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0
-rwxr-xr-x 1 root staff 647K Jan 24  2022 /usr/local/lib/libcurl.so.4.7.0*
-rwxr-xr-x 1 root staff 766K Dec 27  2023 /usr/local/lib/libcurl.so.4.8.0*
```

**Comment by omega8cc** [comment] 2024-08-30 19:17
Can you confirm it the problem is fixed now?

**Comment by fotiDim** [comment] 2024-08-31 18:25
I have run:
```
wget -qO- http://files.aegir.cc/BOA.sh.txt | bash
barracuda up-lts
octopus up-lts all force
reboot
```
and didn't get the error.

**Comment by omega8cc** [comment] 2024-08-31 18:46
Sounds good! Thank you for the confirmation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2024-08-31 18:52 UTC
Labels: type - bug report, status - fixed
