### ISSUE TITLE
Access denied for admin user 1 when accessing the site using domain alias.

### ISSUE THREAD

**Issue by aanjaneyam** [omega8cc/boa#1409] opened 2019-07-16 15:20 UTC
This morning I discovered that I cannot login and access the site as admin using domain alias. This was not the case before. Looks like after running upgrade (up-head) few days ago it seems to have introduced a new change somehow causing the issue. 

Steps to reproduce ( I use varbase as a custom platform for hosting my sites):

1) Add a new domain alias to to an existing site and click save or verify an existing site which already had a working domain alias before the upgrade mentioned above.
2) Visit the site on the alias say at domain.alias.com/user.
3) Input admin username and password and hit enter or click log in. You are redirected to the page `domain.alias.com/admin/dashboard` (as usual) and receive "Access denied - You are not authorized to access this page." message.
3) I go on to search the entire platform and site files and directories to find out what might have changed.
4) After sometime I discover that site verify task (whether on addition on new domain alias or otherwise) is adding a new file `aegir.services.yml` in the docroot/sites/site-name directory. This was not present before. `aegir.serrvices.yml` configures a parameter called `session.storage.options: cookie_domain:. Commented out content of aegir.services.yml is pasted below:

```
---
# This file was automatically generated by Aegir 7.x-3.x
# on Tue, 16 Jul 2019 13:47:06 +0000.

# parameters:
  # session.storage.options:
    # cookie_domain: '.dev.o1.server.domain.com'
```
In the above my main site name is `foo.dev.o1.server.domain.com` so it takes the main site-name, removes the first word and sets the rest as cookie domain including the preceding dot.

5) I open aegir.services.yml and comment out every thing in the file.
6) Rebuild the cache with `drush cr`
7) Visit the above site on its domain alias and log in as user 1 (admin) and you are in. It works after commenting out the contents of `aegir.services.yml`.
8) Re-verify the site with domain alias and the `aegir.services.yml` is re-created.
9) Revisit the site on domain alias after re-verifying in step 8 above and the problem is back with "Access denied - You are not authorized to access this page." message.

My alias is `dev.other-domain.com`; `stage.other-domain.com` and `live.other-domain.com`

**Comment by karudonaldson** [comment] 2019-07-17 21:00
Sounds suspiciously similar to [1406] (https://github.com/omega8cc/boa/issues/1406)

**Comment by omega8cc** [comment] 2019-07-17 21:03
I think it's caused by a bug in Provision: https://www.drupal.org/project/provision/issues/3066538

**Comment by aanjaneyam** [comment] 2019-07-19 18:59
What is the workaround for the time being instead of commenting out the file in question upon every site-verify task.

**Comment by omega8cc** [comment] 2019-07-22 21:32
BOA automatically removes this problematic file now and we have reverted corresponding commits in Aegir.

**Comment by aanjaneyam** [comment] 2019-07-24 10:07
Ok great. I was away. I will test it after running another upgrade. Or the SKYNET Agent would have already done that automatically.

**Comment by omega8cc** [comment] 2020-07-09 22:14
Fixed in Aegir already.

**Closed by omega8cc** 2020-07-09 22:14 UTC
Labels: area - provision, status - not boa specific, type - bug report
