### ISSUE TITLE
entitycache 1.2 to 1.5 upgrade problem

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#868] opened 2016-02-09 06:04 UTC
Updating static platform from Drupal 7.41 to 7.42 caused o_contrib_seven modules to update - entitycache 1.2 to 1.5 most importantly, which required this fix, necessary to update sites db's:

take the files in the o_contrib_seven/entitycache/includes directory and place them in the 
o_contrib_seven/entitycache directory before attempting any site db updates.

Then update all site db's.

Then remove the six files you copied, above.

I don't know how or why the o_contrib_seven modules updated during my recent update of drupal and other non-o_contrib_seven contributed modules to their latest releases?

This is on BOA 2.4.7 stable running php 5.6 and mariaDB 10.x on both octopus and barracuda instances.

**Comment by omega8cc** [comment] 2016-02-10 11:44
The entitycache module is a part of o_contrib_seven, and can be updated in the newer platforms series. The problem is that entitycache changed its files structure, so you may need to disable and uninstall the module before running the migration, or force registry rebuild on the fly. Both not very intuitive, sadly.

**Comment by ar-jan** [comment] 2016-03-13 15:10
As a workaround, I just added entitycache 1.5 to the old platform in sites/all/modules/contrib and ran `drush @your-alias updb -y` for all sites in the platform, then I could migrate to a new platform (I used sites/all in the new platform as well).

**Comment by omega8cc** [comment] 2016-03-13 17:27
This should do the trick (running registry-rebuild on the fly again): https://github.com/omega8cc/provision/commit/8be28a70057ae11063a156a4fb91e7cb6085dbca

**Comment by omega8cc** [comment] 2016-03-14 10:00
Yes, the problem is fixed with this patch applied in Provision.

**Closed by omega8cc** 2016-03-14 10:00 UTC
Labels: area - provision, status - needs work, type - bug report
