### ISSUE TITLE
Aegir tasks queue not running after upgrade to 3.1.1

### ISSUE THREAD

**Issue by leevh** [omega8cc/boa#1015] opened 2016-07-04 06:42 UTC
I realize there are a couple related threads, I wasn't sure whether to reopen or not as I've tried the suggestions.

boa info:
https://gist.github.com/leevh/6b9e52debc1f3e177490cacdb43d2377

Aegir tasks not running at all since 3.1.1 upgrade mid last week.  None of the verify tasks ran after upgrade except server.[myhostname].com  (octopus site host.server.[myhostname].com did not complete verify)
Under hosting -> queues:
Process the queue of outstanding hosting tasks. = 4 days ago
Process the garbage collection of task logs. = 1 week ago

From the other threads I have tried:
- deleting all "stuck" tasks from admin/content
- this patch to run-xdrago https://github.com/omega8cc/boa/commit/5724e897d0b7195b1e0eafbd876126021b4ff20b
- repeatedly tried daily.sh
- re-running barracuda and octopus upgrades
- tried clearing cron semphore, but it doesn't exist https://github.com/omega8cc/boa/issues/998#issuecomment-228534921
- tried clear drush control file https://github.com/omega8cc/boa/issues/998#issuecomment-229703247
- tried /etc/init.d/cron status and drush @hostmaster hosting-cron which both seem fine.
- reboots
- cloudflare was never used
- hosting dispatch commands (https://github.com/omega8cc/boa/issues/998#issuecomment-228534921) did seem to work fine, but after re-run of barracuda and octopus upgrades, the output is currently:
`Using the Drush script found at /opt/tools/drush/8/drush/drush.launcher using pcntl_exec
Loading drushrc "/data/disk/host/.drush/drushrc.php" into "home.drush" scope. [0.02 sec, 2.55 MB]                                                             [bootstrap]
Include /data/disk/host/aegir/distro/019/profiles/hostmaster/modules/aegir/hosting_site_backup_manager/drush [0.04 sec, 2.57 MB]                                 [notice]
Include /data/disk/host/aegir/distro/019/profiles/hostmaster/modules/aegir/hosting_tasks_extra/drush [0.04 sec, 2.57 MB]                                         [notice]
Include /data/disk/host/aegir/distro/019/profiles/hostmaster/modules/aegir/hosting_civicrm/drush [0.04 sec, 2.57 MB]                                             [notice]
Include /data/disk/host/aegir/distro/019/profiles/hostmaster/modules/aegir/hosting_le/hosting_le_vhost/drush [0.04 sec, 2.57 MB]                                 [notice]
Include /data/disk/host/aegir/distro/019/profiles/hostmaster/modules/aegir/hosting_le/drush [0.04 sec, 2.57 MB]                                                  [notice]
Cache HIT cid: 8.2-dev-commandfiles-0-c27970eb523773fb71631eeb1387fa08 [0.04 sec, 2.63 MB]                                                                        [debug]
Could not find the alias @hm [0.13 sec, 5.93 MB]`

I don't think I missed anything from the other threads, and nothing was done to the server besides the upgrade last week (and again tonight).  Anything I should try, or info I could provide?  thanks again!

**Comment by leevh** [comment] 2016-07-07 06:07
Updated boa info gist, updated to Jessie which was successful, but queue is still not processing

**Comment by omega8cc** [comment] 2016-07-07 10:44
Please either run BOA head or don't run stable upgrades after applying fixes, because you continue to overwrite even our hot-fixes. We couldn't reproduce the problem using stable+patches or head, though.

**Comment by omega8cc** [comment] 2016-07-07 10:46
Also, it is probably a duplicate of #998

**Closed by omega8cc** 2016-07-07 10:46 UTC
