### ISSUE TITLE
Unable to run upgrade on dev after dns fix. Coincidence or ?

### ISSUE THREAD

**Issue by AntiNSA** [omega8cc/boa#682] opened 2015-04-12 04:56 UTC
BOA [04:35:20] ==> Aegir on base.thecenterofthenet.com Debian/wheezy x86_64 PHP 5.5

BOA [04:35:26] ==> INFO: The mirror ftp.debian.org doesn't respond, let's try default

BOA [04:37:41] ==> I can not connect to github.com on port 9418 at the moment
BOA [04:37:41] ==> I will try again in 60 seconds, please wait...
BOA [04:37:41] ==> Waiting for attempt 2/4...

BOA [04:39:01] ==> EXIT on error due to ftp.osuosl.org downtime
BOA [04:39:01] ==> Please try to run this script again in a few minutes
BOA [04:39:01] ==> or better yet, hours
BOA [04:39:01] ==> Bye

BOA [04:50:36] ==> INFO: The mirror ftp.debian.org doesn't respond, let's try default

BOA [04:52:51] ==> I can not connect to github.com on port 9418 at the moment
BOA [04:52:51] ==> I will try again in 60 seconds, please wait...
BOA [04:52:51] ==> Waiting for attempt 2/4...

BOA [04:54:11] ==> EXIT on error due to ftp.osuosl.org downtime
BOA [04:54:11] ==> Please try to run this script again in a few minutes
BOA [04:54:11] ==> or better yet, hours
BOA [04:54:11] ==> Bye

**Comment by omega8cc** [comment] 2015-04-13 07:48
Duplicate of #683

**Closed by omega8cc** 2015-04-13 07:48 UTC
