### ISSUE TITLE
jessie_to_stretch fails on head - missing helpers / invalid keyring mariadb 10.2

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1312] opened 2018-12-03 06:07 UTC
The head jessie to stretch fails due to invalid keyring (we think it is the mariadb 10.2 repo on stretch- the keyring isn't valid and the libssl upgrade is no longer compatible with mariadn 10.2 from jessie? - our guess)  upgrade fails with errors (missing helpers, and verify that port 443 is accepting outgoing connections)

boa info more here:  https://gist.github.com/EdNett/995ac0bd6a850a31b374a94ec3998815

Ed

**Comment by EdNett** [comment] 2018-12-03 06:09
I now see this message (I have removed _JESSIE_TO_STRETCH=YES since lsb_release -a shows debian stretch 9.6:

BOA [05:42:14] ==> Skynet Agent v.BOA-3.2.2 welcomes you aboard!
 
BOA [05:42:17] ==> INFO: UPGRADE
 
BOA [05:42:35] ==> VIRT: This system is supported: Linux KVM guest
=== OOPS! ===
It is not any supported Debian or Ubuntu version.
You need Debian Jessie (recommended) or Wheezy.
Also Ubuntu (Trusty or Precise) should work fine,
although BOA developers use and test only Debian.
Bye

**Comment by omega8cc** [comment] 2018-12-03 14:33
Thank you for your early feedback! I hope you didn't try this on a live system, because this feature is still in the debugging mode before upcoming new BOA stable release.

**Comment by yaazkal** [comment] 2018-12-03 14:57
@EdNett fastest beta tester ever of the wild wild git :)

**Comment by omega8cc** [comment] 2018-12-03 15:48
MariaDB is never upgraded during the first phase of major OS upgrade. It happens after your reboot the system and run barracuda upgrade again. At least in theory, once there are no other issues preventing it from working as designed. It's also worth noting that default version used and tested is 10.1 not 10.2, at least not yet.

**Comment by omega8cc** [comment] 2018-12-03 15:58
Also, are you trying to run barracuda stable upgrade after trying upgrade to Stretch? There is no way to see the "You need Debian Jessie (recommended) or Wheezy." if you use barracuda head. There is no stable release including new stuff from head yet, so you need to continue using barracuda head to complete the upgrade.

**Comment by EdNett** [comment] 2018-12-03 16:34
We did ONCE (and only once) try to run an up-stable and that is when we received the above message. This is a test VPS so no problem, that's what we do with this VPS, test. When we try to do an up-head, we receive:
EXIT on error due to missing helpers
Please try to run this script again in a few minutes
Also, make sure that the outgoing connections via port 443 work
Bye

**Comment by EdNett** [comment] 2019-01-18 19:47
Hello,

We're very excited that BOA head is now supporting drupal 8 - we like the lightning distro! We still can't get past the "missing helpers" error message that prevents us from even trying to upgrade our current head which isn't working. It appears that we successfully mugrated from jessie to head, and after manually changing the sources for apt, we have got 10.2 working and up-to-date (mariadb), but we still are stopped immediatedly when trying to run the up-head (which we have tried to do every 3 days for a few weeks now, including today) - we still receive the error messsage:

EXIT on error due to missing helpers
Please try to run this script again in a few minutes
Also, make sure that the outgoing connections via port 443 work
Bye

What deos the "missing helpers" refer to, and can we install them manually?

Thanks,

Ed

**Comment by omega8cc** [comment] 2019-01-24 02:30
Please don't use MariaDB 10.2 if you want PHP 7.1+ until known incompatibility is fixed in either PHP or MariaDB. Please also try to manually upload the BOA.sh.txt script and run it to fix possible DNS issues.

**Comment by omega8cc** [comment] 2019-01-24 02:32
Please note that `_JESSIE_TO_STRETCH` is a work in progress, don't try it on any production system.

**Comment by EdNett** [comment] 2019-01-27 07:42
Hello,

You can close this issue if you like - we no longer have this test vps. We tried downgrading mariadb to 10.1, and then we noticed that you are going to use percona 5.6 ? instead, and we couldn't solve the "missing helpers" error message, either, even when we manually uploaded the BOA.sh.txt script. We couldn't get anything at all to work,( it was a failed jessie to stretch upgrade also) and as it only had 2 GB of ram, it didn't meet new BOA requirements.  As soon as we find an inexpensive test vps with 4 GB of ram, we'll try to install head.

Ed

**Comment by omega8cc** [comment] 2019-01-27 12:11
I would leave this open until we have the feature debugged and working also for MariaDB 10.2 to 10.1 downgrade scenario. We didn’t switch to Percona by default, at least not yet, although the MariaDB 10.2+ compatibility issues with PHP 7.1+ are really surprising and make us want to go with Percona instead.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment] 2020-07-09 22:35
Upgrade to Stretch is working fine for a long time already.

**Closed by omega8cc** 2020-07-09 22:35 UTC
Labels: status - needs work, type - bug report
