### ISSUE TITLE
Edge case with check_boa_php_compatibility()?

### ISSUE THREAD

**Issue by petrowsky** [omega8cc/boa#1606] opened 2021-12-02 00:11 UTC
So, I just hit an issue where I ended up in some type of endless loop trying to do an upgrade. Here's what happened.

For some reason, I had edited **_PHP_MULTI_INSTALL** from "7.3 7.2" to " 7.2" - note the space.

I must have been distracted because I ended up calling barracuda when the line was set to the following.

`_PHP_MULTI_INSTALL=" 7.2"`

I don't know if it was because of the space or some other issue but no matter what, it failed to upgrade and it continually injected that same line value into the .barracuda.cnf file after reporting the failed error. After 3 attempts at changing it to...

`_PHP_MULTI_INSTALL="7.3 7.4"`

The value

`_PHP_MULTI_INSTALL=" 7.2"`

Was replaced and additionally added to the bottom of the file. I'm guessing one of the many sed lines was causing the issue. I was endlessly ending [here](https://github.com/omega8cc/boa/blob/b3fdc7add64e69d8b3a83a8433e1dcc6c44da7ba/lib/functions/helper.sh.inc#L594) despite updating to "7.3 7.4". 

The final solution to get things to work again was to set the following.

```
_PHP_MULTI_INSTALL=
_PHP_SINGLE_INSTALL=7.4
```

However, despite setting it to single install with 7.4 the script still did a multi install of both 7.3 and 7.4 (because 7.3 was previously installed?) Ultimately, the conf file was updated to this.

```
_PHP_MULTI_INSTALL=7.4
_PHP_SINGLE_INSTALL=7.4
```

Anyway, just got the sever to update successfully but thought you might like to know about this edge case.

**Comment by petrowsky** [comment] 2021-12-02 00:13
Maybe it's related to #1603?

**Comment by petrowsky** [comment] 2021-12-02 00:15
Uh oh, looks like something is going on. Check out this output.

```
# grep MULTI .barracuda.cnf
_PHP_MULTI_INSTALL=7.4
_PHP_MULTI_INSTALL=7.4
```

Looks like it's getting injected onto the file somewhere in the script regardless of the space. Even if you get a successful upgrade.

**Comment by petrowsky** [comment] 2021-12-03 01:27
Update: It looks like this is an issue that may be caused by the script. After attempting an update on another box I'm getting the same issue there. And I know that box was using _PHP_MULTI_INSTALL="7.3"

**Comment by lexsoft00** [comment] 2021-12-03 11:39
I'm also getting:
```
_PHP_MULTI_INSTALL=" 7.3"
_PHP_MULTI_INSTALL=" 7.3"
_PHP_MULTI_INSTALL=" 7.3"
```
Whenever I run barracuda up-head before you are asked "Do you want to proceed with the upgrade? [Y/n] n". It also changes everything to PHP 7.3. 

```
VPS Linux KVM guest
  DSK 4/100
  CPU 8
  RAM 15672
  NGX 1.21.4
  PHP 7.3.33
  DBV 5.7.35
  RDS 6.2.6
  SSH 7.4p1
  SSL 1.1.1l
  CRL 7.79.1
  STG _STRONG_PASSWORDS=NO
  CSF _CUSTOM_CONFIG_CSF=NO
  LSH _CUSTOM_CONFIG_LSHELL=NO
  RIS _CUSTOM_CONFIG_REDIS=NO
  SQL _CUSTOM_CONFIG_SQL=NO
  XTR _XTRAS_LIST="ADM CGP CSF IMG FMG GIT CSS SR7"
  MFX _MODULES_FIX=YES
  PFX _PERMISSIONS_FIX=YES
  DNS _DNS_SETUP_TEST=YES
  PKG _EXTRA_PACKAGES=
  CLI _PHP_CLI_VERSION=7.3
  DBS _DB_SERIES=5.7
  TUN _USE_MYSQLTUNER=YES
  BIN _STRICT_BIN_PERMISSIONS=YES
  ARM _SSH_ARMOUR=NO

Thu Dec 2 18:39:56 UTC 2021 / Debian.stretch x86_64 Linux KVM guest / Aegir HEAD / Barracuda BOA-4.1.4-dev / Nginx 1.21.4 / PHP-MI 7.3 / PHP-SE 7.3 / FPM 7.3 / CLI 7.3 / Percona-5.7.35 localhost
Fri Dec 3 11:20:48 UTC 2021 / Debian.stretch x86_64 Linux KVM guest / Aegir HEAD / Barracuda BOA-4.1.4-dev / Nginx 1.21.4 / PHP-MI 7.3 / PHP-SE / FPM 7.3 / CLI 7.3 / Percona-5.7.35 localhost
```

**Comment by lexsoft00** [comment] 2021-12-03 12:12
Switching to Single PHP 7.4 does trigger the install.
```
_PHP_CLI_VERSION=7.4
_PHP_EXTRA_CONF=""
_PHP_FPM_DENY=""
_PHP_FPM_VERSION=7.4
_PHP_FPM_WORKERS=AUTO
_PHP_IONCUBE=NO
_PHP_GEOS=NO
_PHP_MONGODB=NO
_PHP_MULTI_INSTALL=7.4
_PHP_SINGLE_INSTALL=7.4
```

But the install fails:

```
BOA [12:08:50] ==> INFO: PHP 7.4.26 will be installed now
BOA [12:08:50] ==> INFO: Building PHP 7.4.26 from sources, please wait...
BOA [12:08:57] ==> INFO: Building PHP 7.4.26 part 1/3
BOA [12:09:01] ==> INFO: Building PHP 7.4.26 part 2/3
BOA [12:09:19] ==> INFO: Building PHP 7.4.26 part 3/3
BOA [12:09:19] ==> INFO: Building PHP 7.4.26 part 2/3 (again)
sed: can't read /var/opt/php-7.4.26/Makefile: No such file or directory
BOA [12:09:36] ==> INFO: Building PHP 7.4.26 part 3/3 (again)
BOA [12:09:37] ==> WARN: Building PHP 7.4.26 failed!
```
Guess you could use the same method to upgrade to PHP 7.3 but it seems there are issues with 7.4 for now.

**Comment by omega8cc** [comment] 2021-12-13 21:14
Please follow https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by lexsoft00** [comment] 2021-12-14 09:35
OHV VPS 8v cpu 16GB RAM Debian9
https://gist.githubusercontent.com/lexsoft00/70c03500c14435d6a4e276db828b0de4/raw/4edbcc6f018ab07d46ca0b32435ebf844cb8ff97/gistfile1.txt

**Comment by EdNett** [comment] 2021-12-15 10:22
The problem is probably this: (libz missing -cURL being built without libz. ) - so it can't extract packages - 

composer/composer#10153

which means a different version of composer (and perhaps curl ?)

**Comment by EdNett** [comment] 2022-01-12 16:32
php-7.4 still doesn't build on an up head (Jan 12). I can't get any real error messages / reasons why in any log. The terminal command output shows even less now (this on the same vps above - same boa info more - this time with php 7.3 already installed, and then changing the barracuda.cnf file to php7.4 as a single install.:

BOA [15:41:33] ==> INFO: Checking if PHP upgrade is available
BOA [15:41:40] ==> INFO: PHP 7.4.27 will be installed now
BOA [15:41:40] ==> INFO: Building PHP 7.4.27 from sources, please wait...
BOA [15:41:50] ==> INFO: Building PHP 7.4.27 part 1/3
BOA [15:41:54] ==> INFO: Building PHP 7.4.27 part 2/3
BOA [15:41:54] ==> INFO: This PHP 7.4.27 is built with:
BOA [15:41:54] ==> INFO: --with-openssl --with-curl --with-zip --enable-gd --with-jpeg --with-xpm --with-webp --with-freetype --with-ldap --with-gmp --enable-opcache
BOA [15:42:59] ==> INFO: Building PHP 7.4.27 part 3/3
BOA [15:59:19] ==> WARN: Building PHP 7.4.27 failed!

**Comment by omega8cc** [comment] 2022-01-26 16:21
The auto-cleanup procedure for `_PHP_MULTI_INSTALL` has been improved in the meantime and shouldn't cause any further issues.

**Closed by omega8cc** 2022-01-26 16:21 UTC
Labels: type - bug report, status - needs feedback
