### ISSUE TITLE
php-7.4 (used currently as default) does not build properly on head

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1603] opened 2021-11-14 18:57 UTC
php-7.4 (used currently as default) does not build properly and gives errors, so that boa head install and octopus head install do not complete

**Comment by lexsoft00** [comment] 2021-12-04 20:10
BOA [12:08:50] ==> INFO: PHP 7.4.26 will be installed now
BOA [12:08:50] ==> INFO: Building PHP 7.4.26 from sources, please wait...
BOA [12:08:57] ==> INFO: Building PHP 7.4.26 part 1/3
BOA [12:09:01] ==> INFO: Building PHP 7.4.26 part 2/3
BOA [12:09:19] ==> INFO: Building PHP 7.4.26 part 3/3
BOA [12:09:19] ==> INFO: Building PHP 7.4.26 part 2/3 (again)
sed: can't read /var/opt/php-7.4.26/Makefile: No such file or directory
BOA [12:09:36] ==> INFO: Building PHP 7.4.26 part 3/3 (again)
BOA [12:09:37] ==> WARN: Building PHP 7.4.26 failed!

**Comment by EdNett** [comment] 2021-12-06 09:21
I believe that this problem is also preventing Composer from installing any platforms on the command line, since it appears to require php 7.4 that is built with libcurl - and curl is now throwing errors and refusing to download any platforms - so basically this php 7.4 problem has completely broken normal usage of boa.

**Comment by lexsoft00** [comment] 2021-12-06 09:39
True, it's a major bug.

**Comment by omega8cc** [comment] 2021-12-13 21:13
Please follow https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by EdNett** [comment] 2021-12-14 07:17
boa info more is here:
https://gist.github.com/EdNett/bf956818757d4e2e11931cf1b5822ea4

**Comment by lexsoft00** [comment] 2021-12-14 09:34
OHV VPS 8v cpu 16GB RAM Debian9
https://gist.githubusercontent.com/lexsoft00/70c03500c14435d6a4e276db828b0de4/raw/4edbcc6f018ab07d46ca0b32435ebf844cb8ff97/gistfile1.txt

**Comment by EdNett** [comment] 2021-12-14 10:39
see #1609

**Comment by omega8cc** [comment] 2021-12-14 14:30
Please close duplicate issues.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by EdNett** [comment] 2021-12-14 15:16
Hello,  I don't know which is the duplicate, but I wonder if this could be the problem:

https://github.com/composer/composer/issues/10153

**Comment by omega8cc** [comment] 2021-12-16 01:40
Closing as duplicate of https://github.com/omega8cc/boa/issues/1609

**Closed by omega8cc** 2021-12-16 01:40 UTC
Labels: type - bug report, status - needs feedback
