### ISSUE TITLE
How to prevent image showing up directly by typing image url in address bar of browser...

### ISSUE THREAD

**Issue by maninder007** [omega8cc/boa#711] opened 2015-05-10 18:33 UTC
I have a hidden image field in one content type and in manage fields  the Upload destination is set as PRIVATE . IN configuration  --> media --> File system the default download method is set to Private local files served by Drupal..  and the private path is as "sites/ms.domain.com/private/files". 

 I am using the image location from the hidden image field in a Text box to show images.  Everything is fine. But if I copy the image link from browser page  directly to address bar, the image shows up..Is it a normal feature. How to prevent image from showing up directly by typing image url in address bar of browser...

I have searched for hotlink prevention in the site before writing this.. ( I guess something need to be done inside  the nginx_vhost_common.conf file located in octopususer/config/includes/.)

Any help will be appreciated. I hope you would be generous to neglect any ignorant statement from my part.

regards

MP singh

**Comment by omega8cc** [comment] 2015-05-15 14:22
We don't have any hotlink protection in BOA by design. It would create more problems than it is worth of.

Using `private/files` doesn't protect any files these, unless you will switch your site to use private files mode, where all requests go via Drupal for access control.

Furthermore, it would be trivial to fool the protection by sending false referrer along with the request, so it is not worth the effort completely.

**Comment by omega8cc** [comment] 2015-05-15 14:26
Wait, we do protect such files, when the URL matches expected regex.

**Comment by omega8cc** [comment] 2015-05-15 14:28
Please make sure you have cleared caches and that you are logged out and then test this again. If the problem persists, please provide an exact URL to the image for testing it remotely.

**Comment by omega8cc** [comment] 2015-06-09 07:15
Closing because of no feedback for a few weeks. Feel free to reopen if needed.

**Closed by omega8cc** 2015-06-09 07:15 UTC
Labels: status - needs feedback, type - bug report
