### ISSUE TITLE
Backboa AWS S3 backup integration no longer working

### ISSUE THREAD

**Issue by iaminawe** [omega8cc/boa#1138] opened 2017-03-23 03:36 UTC
When I run backboa test it connects to s3 correctly - when I run backboa status I get the following

```
S3ResponseError: S3ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. 
Please use AWS4-HMAC-SHA256.</Message><RequestId>97E3CCF04B7DE922</RequestId><HostId>y++WzVvgF9j8tcPPSWGPMJVWKw9U+Blm4AgqAx6+BbFzWJn40qkAYM34Wg253da1Nr8ka7TiT88=</HostId></Error>

```

I suspect its something Amazon has changed on their side since this funtionality was implemented.

**Comment by omega8cc** [comment] 2017-03-23 10:36
We couldn't reproduce this anywhere, so maybe you need to update your S3 credentials and/or check the access rights on your S3 account?

**Comment by omega8cc** [comment] 2017-03-23 10:39
Try to run [duplicity upgrade](https://github.com/omega8cc/boa/blob/BOA-3.2.0/CHANGELOG.txt#L83).

  `backboa install`

Also, please follow [guidelines](https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt).

**Comment by iaminawe** [comment] 2017-03-23 16:02
Sorry for not following the posting guidelines properly -  here is my boa info https://gist.github.com/iaminawe/e463aba4dbca06fe432c800dd388d9c8

Running backboa install 

> Latest duplicity version 0.7.11 already installed

When I run backboa test 

> Running AWS connection test, please wait...
> OK, I can connect to s3://s3-ca-central-1.amazonaws.com/daily.boa.server.****.world

I think it may be related to the Canada Central region that my bucket is in
This ticket mentions similar issues with the buckets int eh Frankfurt region https://bugs.launchpad.net/duplicity/+bug/1407966

Apparently new regions added after January 2014 only support the AWS4 Signature method.

I will try and delete the bucket and recreate it in another region to test

**Comment by omega8cc** [comment] 2017-03-23 16:11
We have not tested all these new locations, but maybe we should add some warning until duplicity supports them?

**Comment by omega8cc** [comment] 2017-03-23 16:12
By the way, Frankfurt works fine for us.

**Comment by iaminawe** [comment] 2017-03-23 17:33
It seems it has to do with s3-ca-central-1 being a newer datacenter and no longer accepting the V2 AWS Signatures. I just created the same bucket in s3-us-west-2 and when I run backboa status it is able to connect correctly. Thanks for the input

**Comment by omega8cc** [comment] 2017-03-31 23:47
We need to fix this, since it is clearly a bug.

**Comment by omega8cc** [comment] 2017-03-31 23:48
Let's see if this update helps: https://github.com/omega8cc/boa/commit/221be4a8f3a3e8ba9103fb2fbb510f1427bd53fc

**Comment by omega8cc** [comment] 2017-04-04 04:21
This needs more work because we still need to patch newer boto: https://github.com/omega8cc/boa/issues/1141

**Comment by pricejn2** [comment] 2018-02-08 02:03
I can past this error with a simple boto upgrade (tested with latest boto 2.48 via `pip install --upgrade boto`)

However, the next issue is more problematic and appears to be a long standing upstream issue in boto -- https://github.com/boto/boto/issues/2836

```CertificateError: hostname 'daily.boa.srv.foo.bar.s3-ca-central-1.amazonaws.com' doesn't match either of '*.s3.ca-central-1.amazonaws.com', 's3.ca-central-1.amazonaws.com', '*.s3-ca-central-1.amazonaws.com', 's3-ca-central-1.amazonaws.com', '*.s3.dualstack.ca-central-1.amazonaws.com', 's3.dualstack.ca-central-1.amazonaws.com', '*.s3.amazonaws.com'```

You'll notice if you try to browse to https://daily.boa.srv.foo.bar.s3-ca-central-1.amazonaws.com its not a valid cert due to dots in the domain. The simplest workaround may be to change the bucket naming convention to "daily-boa-srv-foo-bar" and just drop the dots all together.

**Comment by pricejn2** [comment] 2018-02-08 05:41
@omega8cc is there a way to disable the backboa script getting overwitten/updated automatically? If not, I'll set up a backboa_custom for my own needs in the meantime.

**Comment by omega8cc** [comment] 2018-07-09 10:30
We have disabled auto-update: https://github.com/omega8cc/boa/commit/5cc6aea10e47c9eb294362c3e1b041ddbdc3f440

**Comment by omega8cc** [comment] 2018-07-09 10:31
PR merged, thanks!

**Closed by omega8cc** 2018-07-09 10:31 UTC
Labels: status - needs work, type - bug report
