### ISSUE TITLE
7.42 autocomplete widget broken over HTTPS

### ISSUE THREAD

**Issue by LunkRat** [omega8cc/boa#869] opened 2016-02-10 16:10 UTC
Changes to the autocomplete widget introduced in Drupal 7.42 (https://www.drupal.org/node/2599326) don't play well with the Nginx config on BOA. 

`Ajax HTTP request terminated abnormally.`

See https://www.drupal.org/node/2599326#comment-10828976

**Comment by omega8cc** [comment] 2016-02-10 16:47
This a Drupal core bug / regression which has to be fixed in core. Not just BOA but Aegir forces clean URLs, and Drupal core should be compatible with its own feature.

**Comment by omega8cc** [comment] 2016-02-10 17:17
It is just insane, see: https://www.drupal.org/node/2599326#comment-10842796

**Comment by LunkRat** [comment] 2016-02-10 17:21
Thank you @omega8cc for the clarification and for posting to the d.o issue with such a clear and convincing argument about it being a core regression!

**Comment by LunkRat** [comment] 2016-02-11 20:58
Please update here when the reverted 7.42 (as mentioned here https://www.drupal.org/node/2599326#comment-10847816) is posted to files.aegir.cc/core as usually linked to on https://omega8.cc/how-to-add-custom-platform-properly-140

**Comment by omega8cc** [comment] 2016-02-11 21:35
Done: https://github.com/omega8cc/7x/commit/0985a53c1a444292c8632ef192907f3fabf7adcb

**Comment by LunkRat** [comment] 2016-02-12 01:14
Thank you @omega8cc! I built my custom platforms using http://files.aegir.cc/core/drupal-7.42.2.tar.gz and everything is working smooth. Hopefully future D7 releases will include a sane solution to the 'problem' that prompted this mess. Cheers.

**Comment by omega8cc** [comment] 2016-02-12 19:44
Thanks for the confirmation. We are testing another workaround: https://www.drupal.org/node/2599326#comment-10850594

**Comment by omega8cc** [comment] 2016-02-20 20:01
@LunkRat For some reason we see inconsistent results, depending on the form tested. Can you share the exact paths / forms to test to experience the problem with vanilla Drupal 7 and BOA 2.4.7 ?

**Comment by ar-jan** [comment] 2016-03-13 21:46
Do you plan to address this in the upcoming release? The nginx workaround would be useful for now, even if there may be a more correct fix.

**Comment by ar-jan** [comment] 2016-03-13 21:50
Two places I notice the problem: any term reference field with the tagging (autocomplete) widget, and file fields configured with filefield_sources (`Autocomplete reference textfield` widget).

**Comment by LunkRat** [comment] 2016-03-14 00:31
@omega8cc we experienced it on term reference and entityreference autocomplete fields.

**Comment by omega8cc** [comment] 2016-03-28 09:39
@ar-jan @LunkRat Thanks! Can you both confirm if the problem persists (for D7 vanilla core, not our D7 fork) when you apply the nginx config workaround? https://www.drupal.org/node/2599326#comment-10850594

**Comment by omega8cc** [comment] 2016-03-28 09:40
Related Provision commits:
https://github.com/omega8cc/provision/commit/d3ee809109e523a24891491d514760ad26397b22
https://github.com/omega8cc/provision/commit/b7c83092558c9fe69b8e27e377fb9e5881a0226f

**Comment by omega8cc** [comment] 2016-03-28 09:47
Note that the Nginx workaround is already present in BOA-2.4.9

**Comment by ar-jan** [comment] 2016-03-28 14:13
I no longer observe this problem on my BOA (v 2.4.9).

(I'm wondering, was this fix included from the start in 2.4.9 or as a hotfix later on? Since I updated to BOA 2.4.9 automatically on 28 Feb, but on 13 March the problem was still there.)

**Comment by omega8cc** [comment] 2016-03-28 15:48
@ar-jan It was included in BOA-2.4.9 from the beginning (see the patches linked above committed on Feb 12, while 2.4.9 was released on Feb 27). Are you testing this using D7 vanilla core or our fork https://github.com/omega8cc/7x ?

**Comment by ar-jan** [comment] 2016-03-28 16:01
I'm using Vanilla Drupal 7. Strange that it didn't work for me two weeks ago. (I have since updated from 7.42 to 7.43, and had a reboot, etc., but that shouldn't matter, I think?). In any case, it does work for me now with Vanilla D 7.43 on BOA 2.4.9.

**Comment by omega8cc** [comment] 2016-03-28 16:31
@ar-jan Weird, but thanks for the confirmation!

**Comment by ar-jan** [comment] 2016-03-30 20:43
Sorry to come back to this, but I just re-encountered the problem. I migrated a site from a platform where I had [patched](https://github.com/omega8cc/7x/commit/0985a53c1a444292c8632ef192907f3fabf7adcb) Drupal core to a new 7.43 without the patch (since this seemed to work for another site). But the problem is still there on the vanilla platform - e.g. trying to add a tag to a node:

> An AJAX HTTP error occurred.
> HTTP Result Code: 301
> Debugging information follows.
> Path: https://www.example.com/index.php?q=en/taxonomy/autocomplete/field_tags
> StatusText: Moved Permanently
> ResponseText: 
> 301 Moved Permanently
> 301 Moved Permanently
> nginx

**Comment by ar-jan** [comment] 2016-03-30 22:15
Oh! This site is https-only, configured as per the docs.

**Comment by omega8cc** [comment] 2016-04-07 00:58
@ar-jan I assume it is fixed then?

**Comment by ar-jan** [comment] 2016-04-07 10:12
No, but my earlier report that it was working was about sites without https. This site has https enforced via local.settings.php. Could that be interfering? Or do the proxy files generated for this site need further changes to include the patch?

**Comment by omega8cc** [comment] 2016-04-07 11:27
@ar-jan The redirect recipe was updated https://github.com/omega8cc/boa/commit/da8f33278a8d8b1cd740de1e93032b237999cc4a

Make sure you have the correct redirect, as shown in this line: https://github.com/omega8cc/boa/blob/master/docs/SSL.txt#L82

**Comment by omega8cc** [comment] 2016-04-07 11:37
In short, these lines were incorrect previously:

`rewrite ^ https://$host$uri? permanent;`
`rewrite ^ https://$host$request_uri permanent;`

This line is correct:

`rewrite ^ https://$host$request_uri? permanent;`

**Comment by omega8cc** [comment] 2016-04-07 11:45
Ah, you don't have http proxy vhost, so for local.settings.php the code didn't change:

`header("Location: https://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);`

To debug this further please comment out the `access_log off;` lines in `/data/disk/o1/config/includes/nginx_vhost_common.conf` and in the SSL proxy vhost, then monitor the access log during debugging to see what exactly happens: `tail -f /var/log/nginx/access.log | grep 301`

**Comment by ar-jan** [comment] 2016-04-10 21:13
After following these steps I get just this line in /var/log/nginx/access.log. I'm adding a node of type blog and enter one letter in the autocomplete tag field:

`"12.34.45.67, 127.0.0.1" mysite.boa.example.com [10/Apr/2016:23:08:13 +0200] "GET /index.php?q=taxonomy/autocomplete/field_tags/l HTTP/1.0" 301 178 847 414 "https://mysite.boa.example.com/node/add/blog" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" 0.000 "-"`

**Comment by omega8cc** [comment] 2016-04-10 22:37
OK, I think there was a reason why `autocomplete` is listed as exception in this very old code: https://github.com/omega8cc/boa/blob/master/aegir/conf/override.global.inc

Furthermore, to avoid this redirect you probably need to add `$base_url = 'https://' . $_SERVER['HTTP_HOST'];` as well.

**Comment by omega8cc** [comment] 2016-04-10 22:50
Please try with the updated code:

```
  // redirect start
  $base_url = 'https://' . $_SERVER['HTTP_HOST'];
  $request_type = ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') ? 'SSL' : 'NONSSL';
  if ($request_type != "SSL" && isset($_SERVER['HTTP_USER_AGENT'])) {
    if (!preg_match("/(?:x-progress-id|ahah|filefield_nginx_progress\/*|tinybrowser|f?ckeditor)/", $_SERVER['REQUEST_URI']) &&
        !preg_match("/(?:tinymce|flowplayer|jwplayer|videomanager|autocomplete|ajax|batch|js\/.*)/", $_SERVER['REQUEST_URI'])) {
      header('X-Accel-Expires: 1');
      header("HTTP/1.1 301 Moved Permanently");
      header("Location: https://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
      header("Connection: close");
      exit;
    }
  }
  // redirect end
```

**Comment by omega8cc** [comment] 2016-04-10 22:53
The question is, do we need these exceptions also when separate HTTPS vhost is used?

**Comment by omega8cc** [comment] 2016-04-10 23:06
We need to check also `QUERY_STRING` on non-clean URLs:

```
  // redirect start
  $base_url = 'https://' . $_SERVER['HTTP_HOST'];
  $request_type = ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') ? 'SSL' : 'NONSSL';
  if ($request_type != "SSL" && isset($_SERVER['HTTP_USER_AGENT'])) {
    if (!preg_match("/(?:x-progress-id|ahah|filefield_nginx_progress\/*|tinybrowser|f?ckeditor)/", $_SERVER['REQUEST_URI']) &&
        !preg_match("/(?:tinymce|flowplayer|jwplayer|videomanager|autocomplete|ajax|batch|js\/.*)/", $_SERVER['REQUEST_URI']) &&
        !preg_match("/(?:x-progress-id|ahah|filefield_nginx_progress\/*|tinybrowser|f?ckeditor)/", $_SERVER['QUERY_STRING']) &&
        !preg_match("/(?:tinymce|flowplayer|jwplayer|videomanager|autocomplete|ajax|batch|js\/.*)/", $_SERVER['QUERY_STRING'])) {
      header('X-Accel-Expires: 1');
      header("HTTP/1.1 301 Moved Permanently");
      header("Location: https://" . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
      header("Connection: close");
      exit;
    }
  }
  // redirect end
```

**Comment by omega8cc** [comment] 2016-04-10 23:13
@ar-jan Still not sure what generates 301 redirect on request which already has `https://` in the referrer

**Comment by ar-jan** [comment] 2016-04-11 20:21
After updating the site's local.settings.php with the latest snippet above I still get a 301 redirect popup. `/var/log/nginx/access.log`:

With language prefix /en:
`"12.34.45.67, 127.0.0.1" mysite.boa.example.com [11/Apr/2016:22:06:50 +0200] "GET /index.php?q=en/taxonomy/autocomplete/field_tags/l HTTP/1.0" 301 178 853 417 "https://mysite.boa.example.com/en/node/add/blog" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" 0.000 "-"`

Without language prefix:
`"12.34.45.67, 127.0.0.1" mysite.boa.example.com [11/Apr/2016:22:11:44 +0200] "GET /index.php?q=taxonomy/autocomplete/field_tags/l HTTP/1.0" 301 178 847 414 "https://mysite.boa.example.com/node/add/blog" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" 0.001 "-"`

Any ideas what else to check?

**Comment by omega8cc** [comment] 2016-04-11 20:59
@ar-jan I don't see any other reason for this redirect, if it is whitelisted. Maybe you have something like secure pages also enabled?

**Comment by ar-jan** [comment] 2016-04-11 21:58
I've now tested on a brand-new site, Drupal 7.43 Standard profile. Then visited the (self-signed) https version of the site, under hostmaster's subdomain (test.boa.example.com). Add an article, add a tag, see a popup ""An AJAX HTTP request terminated abnormally" (not a 301). This site does not have the local.settings.php redirect added.

Also, the moment that the Ajax popup "An AJAX HTTP request terminated abnormally" appears, the Firefox https icon shows a warning "Firefox has blocked parts of this page that are not secure". So it seems that the Ajax request is sent to a http location? That would explain the 301 redirect on the other site, I guess.

**Comment by omega8cc** [comment] 2016-04-11 22:03
@ar-jan Hmm.. please try to add just single line to that test site local.settings.php

```
$base_url = 'https://' . $_SERVER['HTTP_HOST'];
```

It would be interesting to see if this will force Drupal to send the AJAX request via HTTPS?

**Comment by ar-jan** [comment] 2016-04-11 22:11
Ah, after adding this, I get a 301 redirect as before on my other site.

**Comment by omega8cc** [comment] 2016-04-11 22:32
Wait, so `$base_url` forcing https causes that redirect? While the failed AJAX (w/o redirect) is caused by your browser, which refuses to accept plain HTTP connection while you are on https URL? This sounds like browser-side enforced strict HTTPS then?

**Comment by omega8cc** [comment] 2016-04-11 22:35
Then maybe we should remove this line from the SSL recipe?

```
$base_url = 'https://' . $_SERVER['HTTP_HOST'];
```

**Comment by omega8cc** [comment] 2016-04-11 22:37
The question is: why Drupal sends AJAX over plain HTTP while you are on HTTPS?

**Comment by omega8cc** [comment] 2016-04-11 22:38
Either we are missing something obvious here, or there is something weird in the Drupal core.

**Comment by ar-jan** [comment] 2016-04-24 12:23
I've performed this test on a Drupal 7.43 site on a regular budget hoster (with Apache).

Creating/editing a node from the https version of the site has the Ajax request use `https://d7.example.com/index.php?q=taxonomy/autocomplete/field_tags/t` as request URL, as expected. After adding `$base_url = 'https://d7.example.com';` to settings.php, the behavior is the same.

So it seems the problem is not with Drupal, but with something BOA-specific?

**Comment by ar-jan** [comment] 2016-04-24 12:48
Hm, some further sanity checking. A regular site on BOA, without its own certificate, accessed over https using BOA's wildcard certificate, and with `$base_url = 'https://' . $_SERVER['HTTP_HOST'];` added to local.settings.php, does the autocomplete request over https as expected.

**Comment by omega8cc** [comment] 2016-04-25 20:24
@ar-jan Hmm.. so it happens only for sites with real cert and dedicated SSL vhost created with `xboa` tool? Or that it is site specific problem?

Can you show us the SSL vhost for the affected site?

**Comment by ar-jan** [comment] 2016-05-16 12:02
Sorry for the delay. Here it is:

`cat /var/aegir/config/server_master/nginx/pre.d/z_example.com_ssl_proxy.conf`

```
###
### Secure HTTPS proxy (START) example webmaster@example.com
###
server {
  listen                       *:443 ssl http2;
  server_name                  example.com www.example.com;
  ssl                          on;
  ssl_certificate              /etc/ssl/private/example.com.crt;
  ssl_certificate_key          /etc/ssl/private/example.com.key;
  ssl_session_timeout          5m;
  ssl_dhparam                  /etc/ssl/private/example.com.dhp;
  ssl_protocols                TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers                  ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
  ssl_prefer_server_ciphers on;
  ssl_stapling on;
  ssl_stapling_verify on;
  resolver 8.8.8.8 8.8.4.4 valid=300s;
  resolver_timeout 5s;
  keepalive_timeout            70;
  #access_log                   off;
  log_not_found                off;
  location / {
    proxy_pass                 http://149.210.201.198;
    proxy_redirect             off;
    gzip_vary                  off;
    proxy_buffering            off;
    proxy_set_header           Host              $host;
    proxy_set_header           X-Real-IP         $remote_addr;
    proxy_set_header           X-Forwarded-By    $server_addr:$server_port;
    proxy_set_header           X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header           X-Local-Proxy     $scheme;
    proxy_set_header           X-Forwarded-Proto $scheme;
    proxy_pass_header          Set-Cookie;
    proxy_pass_header          Cookie;
    proxy_pass_header          X-Accel-Expires;
    proxy_pass_header          X-Accel-Redirect;
    proxy_pass_header          X-This-Proto;
    proxy_connect_timeout      180;
    proxy_send_timeout         180;
    proxy_read_timeout         180;
  }
}
###
### Secure HTTPS proxy (END)
###
```

**Comment by omega8cc** [comment] 2016-05-17 13:09
@ar-jan It looks perfectly normal and I can't see anything here which could cause problems. It could help if you could double check if the problem is codebase or site specific and if it can be reproduced with blank D7 site with latest Drupal 7.43.2 core.

Anything possibly related to HTTPS (proxy) should be irrelevant very soon anyway, because we have already ready to use Let's Encrypt support (in head) which will use Aegir built-in SSL features, hence docs/SSL.txt will be deprecated /simplified and relevant only when you need dedicated IP (with no TLS SNI dependency).

**Comment by ar-jan** [comment] 2016-05-29 20:21
I have moved this site back to its home on Omega8 hosting now that Let's Encrypt is supported.

With LE https enabled via Aegir control panel (Required) + redirect to www.example.com (as before), the problem no longer appears. So I can no longer reproduce this with the new https configuration (yay!).

The platform and site are the same, so I'd say it *should* be something in the redirect/vhost handling that is now different, but I'm not sure if it's worth it to try to figure out now.

**Comment by omega8cc** [comment] 2016-05-29 20:29
Wow, that is great news! As for the difference, previously it was a local HTTPS proxy, so kind of two servers in a chain. Now it is native HTTPS vhost managed in Aegir, no tricks with local proxy etc. There could be something weird in the way the proxy worked, which caused the problem, if now it no longer happens. Yay!

Thank you for the update!

**Closed by omega8cc** 2016-05-29 20:29 UTC
Labels: area - drupal core, status - needs work, status - not boa specific, type - bug report
