### ISSUE TITLE
head completely broken -ERROR: I can not find PHP-CLI anywhere!

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1608] opened 2021-12-08 06:06 UTC
fresh install of head - php 7.4 does not install , when I try to run a barracuda up-head I get this error:

root@server1:~# barracuda up-head log
ERROR: I can not find PHP-CLI anywhere!

When I login ssh as octopus user and try to run a composer update I get this error:

composer update
/usr/bin/env: ‘php’: No such file or directory

**Comment by lexsoft00** [comment] 2021-12-09 10:05
True, PHP 7.4 does not install your only way is to downgrade to PHP 7.3 ore reinstall with
 `boa in-head public server.domain.com email@domain.com o1 none php-7.3 percona` until they fix head

**Comment by omega8cc** [comment] 2021-12-13 21:15
Please follow https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by EdNett** [comment] 2021-12-14 07:18
boa info more here:
https://gist.github.com/EdNett/bf956818757d4e2e11931cf1b5822ea4

**Comment by EdNett** [comment] 2021-12-14 10:40
see #1609

**Comment by omega8cc** [comment] 2021-12-14 14:30
Please don’t open duplicate issues.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by omega8cc** [comment] 2021-12-16 01:38
Closing as duplicate of https://github.com/omega8cc/boa/issues/1603

**Closed by omega8cc** 2021-12-16 01:38 UTC
Labels: type - bug report, status - needs feedback
