### ISSUE TITLE
Request for guideline re removing old versions of php-fpm, stopping unused versions

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#952] opened 2016-05-23 13:16 UTC
After upgrading BOA, I have a php70-fpm and a php55-fpm which are running which I am not using. I would like to remove the php55-fpm permanently from the system -  Is there a guideline for doing this? 

I would also like to stop the php70-fpm (so that it stays stopped when rebooting). Currently I am simply doing this manually. Do you have a better suggestion. I anticipate using php70-fpm in the future.

boa info more is here:
https://gist.github.com/EdNett/652a06918d9ae9275c4a84ad92c7a953

Thanks for a great BOA!
Ed

**Comment by omega8cc** [comment] 2016-05-23 14:28
Closing as duplicate of #602

**Closed by omega8cc** 2016-05-23 14:28 UTC
