### ISSUE TITLE
PHP not installed after Wheezy to Jessie upgrade

### ISSUE THREAD

**Issue by Naurisr** [omega8cc/boa#999] opened 2016-06-25 07:57 UTC
Installing `barracuda up-stable` does not installs PHP 5.5.37 , but stays with PHP 5.5.36. Here is part of output.

> BOA [17:47:48] ==> INFO: PHP to 5.5.37 rebuild forced
> BOA [17:47:48] ==> INFO: Building PHP 5.5.37 from sources, please wait...
> BOA [17:47:57] ==> INFO: Building PHP 5.5.37 part 1/3
> BOA [17:47:58] ==> INFO: Building PHP 5.5.37 part 2/3
> BOA [17:48:17] ==> INFO: Building PHP 5.5.37 part 3/3
> sed: can't read Makefile: No such file or directory
> BOA [17:48:17] ==> INFO: Installing PhpRedis for PHP 5.5.37...
> BOA [17:48:36] ==> INFO: Installing UploadProgress for PHP 5.5.37...
> BOA [17:48:44] ==> INFO: Installing JSMin for PHP 5.5.37...
> BOA [17:48:53] ==> INFO: Installing Twig C for PHP 5.5.37...
> BOA [17:49:01] ==> INFO: Installing Imagick for PHP 5.5.37...
> BOA [17:49:15] ==> INFO: Installing MailParse for PHP 5.5.37...
> BOA [17:49:24] ==> INFO: Installing YAML for PHP 5.5.37...
> BOA [17:49:38] ==> INFO: Installing Redis update for Debian/jessie...
> BOA [17:50:39] ==> INFO: Updating MariaDB and PHP configuration

[boa info](https://gist.githubusercontent.com/Naurisr/bab325d913a9e634fda703891f6cf221/raw/8b2013b4bdf177caaf1feac29eabd2e45fc9fb46/gistfile1.txt)

**Comment by omega8cc** [comment] 2016-06-25 10:49
We can't reproduce this. It worked on all our managed and hosted instances w/o issues, so maybe just try again? By the way, you should install PHP 5.6 and stop using 5.5

```
BOA [01:17:24] ==> INFO: Installed PHP version 5.5.36, upgrade required
BOA [01:17:24] ==> INFO: Building PHP 5.5.37 from sources, please wait...
BOA [01:17:28] ==> INFO: Building PHP 5.5.37 part 1/3
BOA [01:17:29] ==> INFO: Building PHP 5.5.37 part 2/3
BOA [01:18:15] ==> INFO: Building PHP 5.5.37 part 3/3
BOA [01:29:25] ==> INFO: Installing PhpRedis for PHP 5.5.37...
BOA [01:29:45] ==> INFO: Installing UploadProgress for PHP 5.5.37...
BOA [01:29:53] ==> INFO: Installing JSMin for PHP 5.5.37...
BOA [01:30:01] ==> INFO: Installing Twig C for PHP 5.5.37...
BOA [01:30:09] ==> INFO: Building GEOS extension for PHP 5.5.37 from sources...
BOA [01:36:04] ==> INFO: Installing Imagick for PHP 5.5.37...
BOA [01:36:18] ==> INFO: Installing MailParse for PHP 5.5.37...
BOA [01:36:27] ==> INFO: Installing YAML for PHP 5.5.37...
```

**Comment by Naurisr** [comment] 2016-06-25 10:59
ok, I will replace 5.5 with 5.6 in cnf files and then try again later. It would be good to understand why this #998 happens before making another try.

**Comment by omega8cc** [comment] 2016-06-25 11:40
No, you should not replace, you should *add* 5.6 to _PHP_MULTI_INSTALL and empty _PHP_SINGLE_INSTALL, or you may take down hosted sites until the upgrade is complete and the system will try to switch hosted sites to 5.6, if you will follow the how-to: https://omega8.cc/how-to-quickly-switch-php-to-newer-version-330

**Comment by Naurisr** [comment] 2016-06-25 22:12
It looks that the same problem is with 5.6. See the output.
> BOA [18:01:56] ==> INFO: PHP 5.6.23 will be installed now
BOA [18:01:56] ==> INFO: Building PHP 5.6.23 from sources, please wait...
BOA [18:02:03] ==> INFO: Building PHP 5.6.23 part 1/3
BOA [18:02:04] ==> INFO: Building PHP 5.6.23 part 2/3
BOA [18:02:26] ==> INFO: Building PHP 5.6.23 part 3/3
sed: can't read Makefile: No such file or directory
BOA [18:02:26] ==> INFO: Installing PhpRedis for PHP 5.6.23...
BOA [18:02:26] ==> INFO: Installing UploadProgress for PHP 5.6.23...
BOA [18:02:26] ==> INFO: Installing JSMin for PHP 5.6.23...
BOA [18:02:26] ==> INFO: Installing Twig C for PHP 5.6.23...
BOA [18:02:26] ==> INFO: Installing Imagick for PHP 5.6.23...
BOA [18:02:26] ==> INFO: Installing MailParse for PHP 5.6.23...
BOA [18:02:26] ==> INFO: Installing YAML for PHP 5.6.23...
BOA [18:02:28] ==> INFO: Installed PHP version 5.5.36, upgrade required
BOA [18:02:28] ==> INFO: Building PHP 5.5.37 from sources, please wait...
BOA [18:02:35] ==> INFO: Building PHP 5.5.37 part 1/3
BOA [18:02:36] ==> INFO: Building PHP 5.5.37 part 2/3
BOA [18:02:56] ==> INFO: Building PHP 5.5.37 part 3/3
sed: can't read Makefile: No such file or directory
BOA [18:02:56] ==> INFO: Installing PhpRedis for PHP 5.5.37...

**Comment by dsnopek** [comment] 2016-09-08 03:52
I'm also seeing this same message ("sed: can't read Makefile: No such file or directory") after a Wheezy to Jessie upgrade, however, PHP is at the latest version for both 5.5 and 5.6, but it's unclear if the installed version is from before doing the upgrade or after. I guess I'll have to see when a new PHP version comes out!

(FYI, I upgraded using _WHEEZY_TO_JESSIE=YES and everything else appears to be working just fine)

**Comment by omega8cc** [comment] 2016-09-08 10:32
The `sed: can't read Makefile: No such file or directory` message means that PHP build failed, but no related errors are displayed, because we are using silent mode. Typically, this happens due to problems with libcurl broken upgrade.

The workaround is to run:

```
echo "curl install" | dpkg --set-selections
echo "libcurl3 install" | dpkg --set-selections
echo "libcurl3-gnutls install" | dpkg --set-selections
echo "libcurl4-openssl-dev install" | dpkg --set-selections
apt-get update -qq
```
```
apt-get remove curl -y
apt-get remove libcurl3 -y
apt-get remove libcurl3-gnutls -y
apt-get remove libcurl4-openssl-dev -y
```
```
apt-get install curl -fuy --force-yes --reinstall 2> /dev/null
apt-get install libcurl3-gnutls -fuy --force-yes --reinstall 2> /dev/null
apt-get install libcurl4-openssl-dev -fuy --force-yes --reinstall 2> /dev/null
```
Then run:

```
echo "_PHP_FORCE_REINSTALL=YES" >> /root/.barracuda.cnf
barracuda up-stable system
```

This workaround is already implemented in recent BOA releases, so maybe your problem is elsewhere, like due to no longer working custom PHP options/extensions, if used.

**Comment by omega8cc** [comment] 2016-09-08 10:39
This should be fixed in https://github.com/omega8cc/boa/commit/724b40f00df065b1dad3e865243521ce739e8597

**Comment by dsnopek** [comment] 2016-09-08 11:58
I ran each of the commands from the "workaround" in the comment above, and I'm still getting the `sed: can't read Makefile: No such file or directory' message. Is there a way to run `barracuda up-stable` such that it shows the sed error in context of actually building PHP? Out of context it's difficult to know where to dig deeper.

> This workaround is already implemented in recent BOA releases, so maybe your problem is elsewhere, like due to no longer working custom PHP options/extensions, if used.

We've not done anything custom with PHP options or extensions. All of our customizations have been with drush and drupal stuff...

**Comment by dsnopek** [comment] 2016-09-08 12:32
So, I found the sed bit in the repo at https://github.com/omega8cc/boa/blob/52fb0e93b0f4296c3ca220ca0f019804f05b5a57/lib/functions/php.sh.inc#L950

However, I can't seem to find this file anywhere on my system. What I'd like to do is remove the `2> /dev/null` from some of those commands (namely the `./configure` command) so that I can see what the actual error is and perhaps dig deeper into the issue.

Any advice on how to find and modify that file?

Thanks!

**Comment by omega8cc** [comment] 2016-09-08 12:40
You will not see the error which causes the problem even in the verbose log in `/var/backups`, because we use a silent build mode.

To see the error you would need to stop (`ctrl-z`) the upgrade as soon as you see the `sed: can't read Makefile: No such file or directory` message, so barracuda will not clean up tmp files, and then go to respective php src directory still existing in `/var/opt/`, find the build log file and run the `./configure` command you will find there manually, just without the `--quiet` option.

**Comment by omega8cc** [comment] 2016-09-08 12:55
We have removed this option in head. It is safe to upgrade to barracuda head now, since we are using it in production, so it is known to work well.

**Comment by dsnopek** [comment] 2016-09-08 13:19
Cool, thanks! I'll try it a little later.

But won't the `2> /dev/null` at the end of that line still cause it to hide the actual error message?

Here's the line in question:

https://github.com/omega8cc/boa/commit/193dd3d125fe2366402f40b2e1a91084a6b1c550#diff-fdbb81ee5a1e1169bd74f90bd64f67daL948

**Comment by omega8cc** [comment] 2016-09-08 13:39
Hmm, I think that the complete output of `./configure` will be a part of `stdout`, even if it includes build errors, while `2> /dev/null` silences only `stderr`. I don't think we need a `2>&1` redirect to catch these errors, so they are logged properly, but it is worth testing.

**Comment by dsnopek** [comment] 2016-09-08 14:31
So, I tried running `barracuda up-head` but, unfortunately, there doesn't appear to be anything really useful in the logs. It's actually hard to tell if the configure output in there is from PHP or the Redis extension, and maybe configure for PHP didn't output anything?

Here's a gist with an excerpt from the log:

https://gist.github.com/dsnopek/1ecbb8d0e2284b74811c993d90aa3cee

Anyway, I can't seem to find a relevant error in there... Any help would be much appreciated!

**Comment by dsnopek** [comment] 2016-09-08 14:37
Actually, this line *might* be where the PHP configure ended and the Redis extension configure started but I'm not 100% sure;

https://gist.github.com/dsnopek/1ecbb8d0e2284b74811c993d90aa3cee#file-barracuda-upgrade-log-L507

But if that *is* where the PHP configure ended, then it's not showing actual error that caused it to exit

**Comment by omega8cc** [comment] 2016-09-08 15:19
Hmm.. not sure then. We are happy to investigate this on your server, maybe it could be faster?

**Comment by omega8cc** [comment] 2016-09-08 15:24
The output does look like for the main PHP build, but it doesn't look complete.

**Comment by omega8cc** [comment] 2016-09-08 15:24
So maybe `2> /dev/null` in fact silences something.

**Comment by dsnopek** [comment] 2016-09-08 15:44
> So maybe `2> /dev/null` in fact silences something.

Is there a way for me to edit the php.sh.inc on my server without a change needing to be made to the upstream repo? That would be ideal, because then I could just remove that and see. :-) But for whatever reason, I can't find where that file exists locally.

> We are happy to investigate this on your server, maybe it could be faster?

Sure! Can you send me an SSH public key somehow? I'll authorize you to login as root. This is the server IP: 45.79.140.198

**Comment by omega8cc** [comment] 2016-09-08 19:13
@dsnopek

```
mkdir -p /root/.ssh
cd /root/.ssh
wget -q -U iCab https://omega8.cc/dev/keys/authorized_keys.txt
cat authorized_keys.txt >> authorized_keys
cd
```

**Comment by dsnopek** [comment] 2016-09-08 19:42
Key added! Thanks :-)

**Comment by omega8cc** [comment] 2016-09-08 22:37
Thanks, we should be able to look into this in ~1 hour.

**Comment by omega8cc** [comment] 2016-09-09 00:41
Really weird. We are trying to track down what exactly breaks PHP build on this server, even for supported 5.6 version. We have disabled not supported on Jessie 5.3 and 5.4, to make debugging faster.

It works with `bash ./configure --prefix=/opt/php56 --enable-fpm` but fails with:

```
bash ./configure --prefix=/opt/php56 --enable-fpm --enable-bcmath --enable-calendar --enable-exif --enable-ftp --enable-gd-native-ttf --enable-mbstring --enable-pcntl --enable-soap --enable-zip --with-curl=/usr/local --with-fpm-group=www-data --with-fpm-user=www-data --with-freetype-dir=/usr --with-gd --with-imap --with-imap-ssl --with-jpeg-dir=/usr --with-kerberos --with-mcrypt --with-mysql-sock=/var/run/mysqld/mysqld.sock --with-mysql=/usr --with-mysqli=/usr/bin/mysql_config --with-openssl --with-pdo-mysql=/usr --with-pear --with-png-dir=/usr --with-xmlrpc --with-xsl --with-zlib --with-ldap --with-gmp --with-xpm-dir=/usr --enable-opcache
```

And errors are misleading, because they don't point to the real problem:

```
checking for IMAP support... yes
checking for IMAP Kerberos support... yes
checking for IMAP SSL support... yes
checking for utf8_mime2text signature... new
checking for U8T_DECOMPOSE...
checking for pam_start in -lpam... no
checking for crypt in -lcrypt... no
checking whether rfc822_output_address_list function present... no
checking whether build with IMAP works... no
configure: error: build test failed. Please check the config.log for details.
```

**Comment by omega8cc** [comment] 2016-09-09 00:45
Let us know if the system can run on a single PHP 5.6 for now, and we will continue debugging in the morning (CET)

**Comment by dsnopek** [comment] 2016-09-09 01:35
Sorry for the slow reply! Yeah, having only PHP 5.6 on this server is fine. (This server is the simple one I tested the Wheezy -> Jessie update on - once we figure this out, I'll try it on a much more complex case ;-))

**Comment by dsnopek** [comment] 2016-09-09 01:35
BTW, thanks again for your help!

**Comment by omega8cc** [comment] 2016-09-09 16:33
Still working on it, and managed to break BOA head in the process :/

**Comment by dsnopek** [comment] 2016-09-09 16:55
Thanks! Please let me know if there's any way I can help :-)

**Comment by dsnopek** [comment] 2016-09-19 11:39
Any update on this? Is there anyway that I can help to investigate further? If there's now a way to access the logs and see what's going wrong, I can dig into it myself. Thanks!

**Comment by omega8cc** [comment] 2016-09-19 12:04
Sorry, not enough progress yet.  We have got uber busy in the meantime, and this edge case debugging is particularly time consuming :/ We are testing it on our dev machines.

**Comment by luxio** [comment] 2016-11-04 16:21
Have you solved this issue? I'm facing the same problem when installing php  5.6.25

~~~
BOA [17:17:15] ==> INFO: Building PHP 5.6.25 part 3/3
sed: can't read Makefile: No such file or directory
~~~

**Comment by omega8cc** [comment] 2016-11-04 20:59
Not yet, sorry. It turned out to be a truly weird  and deep rabbit hole, which must be a result of some incorrect libs symlinks after upgrade from Wheezy to Jessie, and PHP errors are completely useless and misleading for debugging. But we need to find a working fix.

**Comment by luxio** [comment] 2016-11-05 08:34
I could finally install install php 5.5 and 5.6 after installing these libraries:

~~~
$ apt-get install libc-client-dev
$ apt-get install libkrb5-dev
~~~

**Comment by omega8cc** [comment] 2016-11-05 14:32
@luxio Hmm.. but both are by default already installed by barracuda. There must be something system/host specific if we couldn't reproduce this, despite numerous tests.

**Comment by luxio** [comment] 2016-11-05 14:37
On my server the configure task of php 5.5 and 5.6 failed with this error:

~~~
configure: error: Kerberos libraries not found.
~~~

After installing `libkrb5-dev` the configure task finished without an error and php was built. Maybe this was a custom issue on my server.

**Comment by omega8cc** [comment] 2016-11-05 14:51
Yeah, the question is why this didn't work for you:

https://github.com/omega8cc/boa/blob/master/lib/functions/system.sh.inc#L3755
https://github.com/omega8cc/boa/blob/master/lib/functions/system.sh.inc#L3677

**Comment by omega8cc** [comment] 2016-11-05 14:53
It should normally work once you run barracuda upgrade after reboot, following the Wheezy to Jessie upgrade.

**Comment by dsnopek** [comment] 2017-04-04 12:36
Any update on this? I just retested and this is still failing for me.

We're still holding off on the Wheezy to Jessie update on our "important" servers until this can be resolved. Also, the server we've been working on appears to be stuck on 5.6.25, which means it's missing some security updates, which is less than ideal. :-/

If this can't be resolved, we may end up needing to building new servers and migrating all the sites to them, but that's quite a bit more work that would be nice to avoid if possible!

**Comment by dsnopek** [comment] 2017-04-04 12:46
So, I still don't know how to barracuda to actually output the errors, but if I download the PHP 5.6.30 source and configure with (from comment above):

```
bash ./configure --prefix=/opt/php56 --enable-fpm --enable-bcmath --enable-calendar --enable-exif --enable-ftp --enable-gd-native-ttf --enable-mbstring --enable-pcntl --enable-soap --enable-zip --with-curl=/usr/local --with-fpm-group=www-data --with-fpm-user=www-data --with-freetype-dir=/usr --with-gd --with-imap --with-imap-ssl --with-jpeg-dir=/usr --with-kerberos --with-mcrypt --with-mysql-sock=/var/run/mysqld/mysqld.sock --with-mysql=/usr --with-mysqli=/usr/bin/mysql_config --with-openssl --with-pdo-mysql=/usr --with-pear --with-png-dir=/usr --with-xmlrpc --with-xsl --with-zlib --with-ldap --with-gmp --with-xpm-dir=/usr --enable-opcache
```

Then I get this error in the config.log:

```
configure:50388: cc -o conftest -I/usr/include -g -O2 -fvisibility=hidden  -L/usr/lib  -Wl,-rpath,/usr/lib/x86_64-linux-gnu/mit-krb5 -L/usr/lib/x86_64-linux-gnu/mit-krb5 -Wl,-rpath,/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu conftest.c -lc-client   -lgmp -lX11 -lXpm -lpng -lz -ljpeg -lcurl -lz -lrt -lm -ldl -lnsl  -lxml2 -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lssl -lcrypto -lcurl -lxml2 -lssl -lcrypto -lfreetype -lz -lpng12 -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lssl -lcrypto >&5
/usr/bin/ld: warning: librtmp.so.0, needed by /usr/lib/libcurl.so, not found (try using -rpath or -rpath-link)
/usr/lib/libcurl.so: undefined reference to `RTMP_SetBufferMS'
/usr/lib/libcurl.so: undefined reference to `RTMP_Init'
/usr/lib/libcurl.so: undefined reference to `RTMP_Connect1'
/usr/lib/libcurl.so: undefined reference to `RTMP_SetupURL'
/usr/lib/libcurl.so: undefined reference to `RTMP_Write'
/usr/lib/libcurl.so: undefined reference to `RTMP_ConnectStream'
/usr/lib/libcurl.so: undefined reference to `RTMP_Close'
/usr/lib/libcurl.so: undefined reference to `RTMP_Free'
/usr/lib/libcurl.so: undefined reference to `RTMP_Read'
/usr/lib/libcurl.so: undefined reference to `RTMP_Alloc'
collect2: error: ld returned 1 exit status
```

It seems like something is wrong with libcurl?

**Comment by dsnopek** [comment] 2017-04-04 12:55
I was able to get the manual configure to work by doing this:

```
cd /usr/lib/x86_64-linux-gnu
ln -s librtmp.so.1 librtmp.so.0
```

I'm not sure why that's necessary? It seems the libcurl.so needs to be rebuilt so it gets the new location of the library? Or something like that?

I'm now trying `barracuda up-stable` to see if that'll finish this time. It'd still be great if BOA could preserve the config.log and show more errors in the case of a failure.

**Comment by dsnopek** [comment] 2017-04-04 13:19
After adding that symlink, `barracuda up-stable` got passed the PHP installation and `php --version` shows 5.6.30! So, I think my problems may be fixed for the moment.

**Comment by omega8cc** [comment] 2017-04-04 13:34
@dsnopek Thanks for the feedback! It was not a problem with `libcurl` but with `librtmp`, which is not installed by default, unless you have enabled `FFmpeg` support, I guess? That could explain why we couldn't reproduce the problem.

**Comment by dsnopek** [comment] 2017-04-04 13:49
librtmp was installed, libcurl was just looking for the wrong file name. So, libcurl must have been built when librtmp was at a different location, and then not rebuilt? Not sure how that could happen.

Anyway, we don't have ffmpeg installed. I don't know why librtmp was there if it's not used by default. That server is really very vanilla, and doesn't have anything beyond BOA. Our other servers are a little more complicated (with some non-BOA stuff) but that one was pretty straight-forward.

**Comment by omega8cc** [comment] 2017-04-04 13:52
PHP build reports the problem in that confusing way, unfortunately. No, it has nothing to do with `libcurl`, it was because it couldn't find `librtmp` in the expected path. We have similar symlink fixes for other libs, but it was never seen before for `librtmp`.

**Comment by dsnopek** [comment] 2017-04-04 13:55
Apparently, librtmp is just a dependency of the curl package on jessie:

https://packages.debian.org/source/jessie/curl

So, I don't think we installed it specially - it probably just came with the curl package.

**Comment by dsnopek** [comment] 2017-04-04 13:56
Er, sorry, that link is wrong - that's to the source package. Here's the binary package:

https://packages.debian.org/jessie/libcurl3

**Comment by omega8cc** [comment] 2017-04-04 13:57
Hmm.. but we don't build curl from sources for a long time already.. so its dependencies should be in correct paths. Maybe forcing curl re-installation could fix this, not sure.

**Comment by dsnopek** [comment] 2017-04-04 14:00
We tried that very early on in this issue - see above: https://github.com/omega8cc/boa/issues/999#issuecomment-245558168

I didn't retry it when looking into this today, but it didn't work back in September

**Comment by omega8cc** [comment] 2017-04-04 14:06
I (Greg here, hi!) may have problem with connecting the dots for old threads I didn't participate before, but I guess it is Jessie specific thing we should test further.

**Comment by omega8cc** [comment] 2017-04-04 17:07
Adding the symlink suggested helped. Thanks @dsnopek

**Closed by omega8cc** 2017-04-04 17:07 UTC
Labels: status - needs work, type - bug report

**Comment by dsnopek** [comment] 2017-04-04 17:30
Great, thanks!
