### ISSUE TITLE
Can't access files.aegir.cc from one of my servers

### ISSUE THREAD

**Issue by santo74** [omega8cc/boa#692] opened 2015-04-21 19:44 UTC
On one of my servers I can't perform any updates anymore with 
```
barracuda up-stable system
```
because it can't access files.aegir.cc:
```
INFO: The mirror files.aegir.cc doesn't respond, let's try default
ERROR: files.aegir.cc is not available, please try later
```

I tried from another server (same hosting provider) and there I have no issues at all.
The last successful update on the affected system was on April 11

**Comment by omega8cc** [comment] 2015-04-21 20:01
This looks like a duplicate of #685

**Closed** 2015-04-21 20:02 UTC
Labels: status - duplicate, type - question

**Comment by santo74** [comment] 2015-04-21 20:10
I'm afraid it's not.
The issue remains even after performing the csf update as mentioned in #685

**Comment by omega8cc** [comment] 2015-04-21 20:56
What is the result of:

`curl -I files.aegir.cc`

**Comment by santo74** [comment] 2015-04-21 21:07
```
# curl -I files.aegir.cc
curl: (7) couldn't connect to host
```

As a test:
```
# curl -I www.omega8.cc
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Tue, 21 Apr 2015 21:06:01 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https://www.omega8.cc/
```

And FYI:
```
# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Comment by omega8cc** [comment] 2015-04-21 21:09
I have asked for: `host -a files.aegir.cc`

**Comment by omega8cc** [comment] 2015-04-21 21:10
Please send your system IP address to omega8cc at gmail dot com

**Comment by santo74** [comment] 2015-04-21 21:11
output of host command:

```
# host -a files.aegir.cc
Trying "files.aegir.cc"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30135
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 4

;; QUESTION SECTION:
;files.aegir.cc.                        IN      ANY

;; ANSWER SECTION:
files.aegir.cc.         35      IN      A       104.245.208.226

;; AUTHORITY SECTION:
aegir.cc.               900     IN      NS      ns1.host8.biz.
aegir.cc.               900     IN      NS      ns2.host8.biz.
aegir.cc.               900     IN      NS      ns3.host8.biz.
aegir.cc.               900     IN      NS      ns4.host8.biz.

;; ADDITIONAL SECTION:
ns1.host8.biz.          90      IN      A       134.19.164.236
ns2.host8.biz.          90      IN      A       50.31.233.231
ns3.host8.biz.          90      IN      A       50.31.251.116
ns4.host8.biz.          90      IN      A       104.245.208.226

Received 193 bytes from 127.0.0.1#53 in 138 ms
```

**Comment by omega8cc** [comment] 2015-04-21 21:12
OK, so at least DNS cache server works properly.

**Comment by omega8cc** [comment] 2015-04-21 21:14
Also, please check this:

`csf -g 104.245.208.226`

**Comment by santo74** [comment] 2015-04-21 21:15
```
# csf -g 104.245.208.226

Chain            num   pkts bytes target     prot opt in     out     source               destination

DENYIN           97       0     0 DROP       all  --  !lo    *       104.245.208.226      0.0.0.0/0

DENYOUT          97       8   480 LOGDROPOUT  all  --  *      !lo     0.0.0.0/0            104.245.208.226

csf.deny: 104.245.208.226 # lfd: (PERMBLOCK) 104.245.208.226 (US/United States/unknown.scnet.net) has had more than 4 temp blocks in the last 86400 secs - Sun Apr 12 15:24:00 2015
```

**Comment by omega8cc** [comment] 2015-04-21 21:15
Hah

**Comment by omega8cc** [comment] 2015-04-21 21:16
Please run:

`csf -df`
`csf -tf`

**Comment by santo74** [comment] 2015-04-21 21:16
So it does seem similar to #685 but the csf update didn't solve the problem

**Comment by omega8cc** [comment] 2015-04-21 21:17
Because your system already blocked main download mirror.

**Comment by santo74** [comment] 2015-04-21 21:19
I see. Now it works correctly indeed.
Thanks for your help!

**Comment by omega8cc** [comment] 2015-04-21 21:19
NP
