### ISSUE TITLE
Scheduled backup won't work anymore after upgrade from 2.4 to 3.1

### ISSUE THREAD

**Issue by florisvanwoudenberg** [omega8cc/boa#1000] opened 2016-06-25 08:20 UTC
After the upgrade the scheduled backup won't work.The garbage collection is working fine, but no scheduled backups.
Manual backup is working fine.
This happens on all upgraded servers.
Any idea

**Comment by cvining** [comment] 2016-06-25 08:26
This may be related to issue #901,

**Comment by omega8cc** [comment] 2016-06-25 10:45
Yes, it is a duplicate of #901

**Closed by omega8cc** 2016-06-25 10:45 UTC
