### ISSUE TITLE
Migration: xboa supports only Aegir 2.x / BOA-2.4.x Octopus instances

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#960] opened 2016-05-28 14:27 UTC
I' trying to migrate a site following the instructions at https://github.com/omega8cc/boa/blob/master/docs/MIGRATE.txt

When I import the sites with 

`xboa import o1 target-ip`

I get this error:

~~~
INFO: site site.example.com db_host on o1 fixed
INFO: site site.example.com db setup on o1 complete
INFO: site site.example.com db import on o1 complete
This task is not valid                                             [error]
INFO: site site.example.com verify on o1 scheduled
~~~

The sites are not listened in the octopus frontend.
At which step during the migration will the sites and platforms be imported in the hostmaster db?
I have installed boa with the boa command which created an octopus instance for o1. Is this the problem? Does the target octopus instance must not exist before the migration, even if it is empty.  

Here is my [config](https://gist.github.com/luxio/37edf7d45ccdfb142232ea95b2b8b153)

**Comment by omega8cc** [comment] 2016-05-28 16:54
>> Does the target octopus instance must not exist before the migration?

Yes, it must not exist on the target. We have explained this in the docs, and thus there is no additional protection from trying something like this (overwriting existing instance).

**Comment by luxio** [comment] 2016-05-29 06:48
I have done the migration again. This time the target instance did not exist exist. But I'm still getting the same error.

Any ideas?

**Comment by omega8cc** [comment] 2016-05-29 10:38
The "this task is not valid" error usually happens when related drush alias name is truncated (too long) so the alias in the database doesn't match the drush alias filename. But it shouldn't really happen in Aegir 3.x, so maybe the problem is elsewhere. For example: the drush alias definition is missing in the hostmaster table (for the hostmaster itself), so all the rest falls apart, because it can't find its own reference. No idea why you see this, though. We have never seen this during migrations.

**Comment by luxio** [comment] 2016-05-29 10:59
>  For example: the drush alias definition is missing in the hostmaster table (for the hostmaster itself)

Yes, the `hosting_site_alias`table is empty.

At which step is the hostmaster database imported? Shouldn't the source hostmaster db be imported at first with the command `xboa import o1 target-ip`?

**Comment by omega8cc** [comment] 2016-05-29 12:17
Hmm.. I will see if we can reproduce this. We have not updated these procedures since BOA-2.4, so maybe there is some incompatibility with D7 based Aegir we need to fix, not sure.

**Comment by luxio** [comment] 2016-05-29 12:24
There was an error when dumping the source postmaster db, which caused the `prev_hostmaster.sql` to be empty. The dump failed because there were these tables missing in the database: `comments`, `node_revisions`, `node_counter` and `node_revisions`. I don't know why there are missing. Any Ideas how to recreate these tables without breaking the postmaster db.

**Comment by omega8cc** [comment] 2016-05-29 12:28
Yeah, these are Drupal 6 specific tables, they don't exist in Drupal 7. We need to make the `xboa` aware of Aegir version it is trying to migrate.

**Comment by omega8cc** [comment] 2016-06-08 13:13
This has been fixed in head.

**Closed by omega8cc** 2016-06-08 13:13 UTC
Labels: status - fixed, type - bug report

**Comment by omega8cc** [comment] 2016-06-08 13:15
Note: now it is opposite -- it supports only BOA-3.1.0 or newer.
