### ISSUE TITLE
error: nginx: [emerg] invalid number of arguments in "fastcgi_param" on sites with CiviCRM enabled

### ISSUE THREAD

**Issue by zkrebs** [omega8cc/boa#543] opened 2014-12-19 23:46 UTC
After upgrading my BOA master and octopus approx 3 weeks ago, there were no errors on the upgrade, but when it went through to reverify my platforms/sites a few of them have this problem. I ran another update today, and experienced the same issue. Deleting the vhost file and re-verifying does not fix, the same error is produced.

I'm using STABLE

nginx on my.domain.com could not be restarted. Changes might not be available until this has been done. (error: nginx: [emerg] invalid number of arguments in "fastcgi_param" directive in /data/disk/bagua/config/server_master/nginx/vhost.d/mydomain.com:12
nginx: configuration file /etc/nginx/nginx.conf test failed)

UPDATE: Following the bug submission guidelines as best as possible now.

SERVER:

I'm on Linode, with a 4GB plan. 
Linux version 3.16.5-x86_64-linode46 (maker@build) (gcc version 4.7.2 (Debian 4.7.2-5) ) #1 SMP Mon Oct 13 09:42:16 EDT 2014

Barracuda Conf: https://gist.github.com/zkrebs/de5a611ff671931640f8
Barracuda Log: https://gist.github.com/zkrebs/da80a80788ac9fbd892e
User Octopus Conf: https://gist.github.com/zkrebs/37520de5bc5c3056a278
Octopus Log: https://gist.github.com/zkrebs/03f06c545eafbf5e44b3

**Comment by omega8cc** [comment] 2015-01-05 23:49
These errors suggest that something is really broken there. But it is hard to tell what exactly. We could probably take a look if you could add our SSH keys and send us your server IP address: omega8cc at gmail dot com.

```
mkdir -p /root/.ssh
cd /root/.ssh
wget -q -U iCab http://omega8.cc/dev/keys/authorized_keys.txt
cat authorized_keys.txt >> authorized_keys
```

**Comment by zkrebs** [comment] 2015-01-12 23:17
I can do this very soon - should I clear my platforms into static first before you take a look?

**Comment by omega8cc** [comment] 2015-01-13 18:47
Indeed, the `db_port` line doesn't have a 3306 after running verify on the affected site:

>>  fastcgi_param db_port   ;

but there is another problem there, which could be either the real source of the problem or a result of Aegir own bug:

```
Calling hook drush_provision_civicrm_post_provision_verify
CiviCRM: found civicrm in packages
CiviCRM: civicrm is in /data/disk/USER/distro/oa.004/pressflow-6.22.104/sites/all/modules/civicrm
Drush command terminated abnormally due to an unrecoverable error. Error: Call to undefined function _civicrm_init() in /data/disk/USER/.drush/xts/provision_civicrm/verify.provision.inc, line 70
The external command could not be executed due to an application error.
```

Do you use civicrm in this site? if not, maybe remove it to make the debugging easier?

**Comment by omega8cc** [comment] 2015-01-13 18:51
This happens only for sites with civicrm present.

**Comment by omega8cc** [comment] 2015-01-13 19:11
I see that these sites do use civicrm, so removing it is not an option. I hope that this issue will be automagically fixed in BOA-2.4.0 which comes with newer versions of `provision_civicrm` and `hosting_civicrm`, plus updated Aegir Provision.

**Comment by omega8cc** [comment] 2015-01-13 19:14
That said, your Octopus instance doesn't really run 2.3.8 version, because the upgrade partially failed.

Should we try to run it again?

**Comment by omega8cc** [comment] 2015-01-13 19:19
Plus, this mess will cause problems:

```
root@tao:/data/disk/bagua/distro# ls -la
total 60K
drwx--x--x 15 bagua users 4.0K Dec 29 20:31 ./
drwx--x--x 22 bagua users 4.0K Jan  5 16:04 ../
drwx--x--x  8 bagua users 4.0K Aug 14  2013 001/
drwx--x--x  7 bagua users 4.0K Apr 25  2013 002/
drwx--x--x  7 bagua users 4.0K Apr 19  2013 003/
drwx--x--x  4 bagua users 4.0K Sep 30 03:07 004/
drwx--x--x  7 bagua users 4.0K Mar  8  2013 005/
drwx--x--x  8 bagua users 4.0K Dec 11  2013 006/
drwx--x--x  7 bagua users 4.0K Feb 19  2014 007/
drwx--x--x  8 bagua users 4.0K Jul  8  2014 009/
drwx--x--x  8 bagua users 4.0K Nov 26 15:12 010/
drwx--x--x  3 bagua users 4.0K Dec 29 20:36 011/
drwx--x--x 20   116 users 4.0K Oct 28  2011 oa.002/
drwx--x--x  5   116 users 4.0K Sep 30 02:58 oa.003/
drwxr-xr-x 17 bagua users 4.0K Feb  9  2012 oa.004/
```

You should move these non-standard directories oa.002, oa.003 and oa.004 to /data/disk/bagua/static and re-add affected platforms and sites in Aegir (you can't edit their paths while they exists in Aegir).

**Comment by zkrebs** [comment] 2015-01-13 19:26
Okay, thank you for all your work! I can wait until BOA 2.4 - as long as
the sites ' run' they don't have to verify officially.

Please do try the upgrade again!

Zachary Krebs
Phone: ~ *M-F* *8-5PM ~* (541 )708-1163

**Comment by zkrebs** [comment] 2015-01-13 19:27
I will move the directories to standard location, I put them there long ago
when I had no idea what I was doing and was afraid to move them :(

Zachary Krebs
Phone: ~ *M-F* *8-5PM ~* (541 )708-1163

**Comment by zkrebs** [comment] 2015-01-17 00:30
Why does my /user/login redirect to a SSL page on my sites, when I do not
have SSL configured for these domains?

Zachary Krebs
Phone: ~ *M-F* *8-5PM ~* (541 )708-1163

**Comment by omega8cc** [comment] 2015-01-19 10:23
OK, we need to figure it out before 2.4.0 release then, to make sure we don't introduce some unidentified regression related to CiviCRM support. I don't think it is related to using non-standard directory structure, though. Rather to some (hopeful old and already fixed elsewhere) Aegir or CiviCRM integration code bug.

If you allow, we would be happy to run upgrade to (generally) stable BOA head on your system, so we could get a proof that the issue is indeed fixed in current Aegir and CiviCRM integration code.

**Comment by omega8cc** [comment] 2015-01-19 10:25
As for the SSL redirects. BOA doesn't do this for any site other than hostmaster. It must be a result of using contrib module and settings which force such redirect. It is OT, though.

**Comment by zkrebs** [comment] 2015-01-19 16:47
Please do!

Zachary Krebs
Phone: ~ *M-F* *8-5PM ~* (541 )708-1163

**Comment by zkrebs** [comment] 2015-01-19 21:49
Very weird, I have combed through my site www.transformationarts.org and I am not seeing any modules which turn on SSL - I do not have secure pages installed or enabled.

When I turn on my CiviCRM, I see in the admin menu errors - it can't load image icons. For whatever reason it is trying to load them from SSL which of course is just the default certificate provided by Aegir, which gives an error. I only noticed this issue after the last upgrade, was working fine before.

https://www.transformationarts.org/sites/all/modules/civicrm/packages/jquery/css/images/arrow.png

**Comment by omega8cc** [comment] 2015-01-19 22:06
Please don't add unrelated comment to this issue. I have no idea what the problem is with SSL in that site, but we can't debug this further for you after we have fixed the main problem with this workaround: https://github.com/omega8cc/provision/commit/a6941aeed7828800c287ea58107ffd2efa7831d2

**Closed by omega8cc** 2015-01-19 22:06 UTC
Labels: status - needs feedback, status - needs work, type - bug report
