### ISSUE TITLE
Commerce Kickstart - demo content 

### ISSUE THREAD

**Issue by Juc1** [omega8cc/boa#669] opened 2015-03-24 14:25 UTC
Hi all,

When installing Commerce Kickstart on a non-BOA site the install screen asks "Do you want to install the demo store?" Yes / No

Is that option available in BOA? So far I have not seen it and so the site installs with the demo content. On a non-BOA site I can remove the demo content with the "wipe all content" link at /admin/commerce/config/demo but in a BOA site (in several different BOA installs) this link gives a 404 and seems to destroy (empty) the database. This is a problem because the "wipe all content" link is the [only way to delete the demo content](https://drupalcommerce.org/questions/4822/deleting-demo-store-categories-and-product-types).

Any ideas please?

Thanks...

/admin/commerce/config/demo = 

![/admin/commerce/config/demo](http://i.imgur.com/IBxUXg9.jpg) 

non-BOA site

![non-boa site](http://i.imgur.com/L4cJSZS.jpg)

 
non-BOA site

![non-boa site](http://i.imgur.com/RFbF40b.jpg)

BOA site

![boa site](http://i.imgur.com/2pOQazF.jpg)

**Comment by Juc1** [comment] 2015-03-24 17:06
PS - to reproduce the destroyed database problem:

install the Commerce Kickstart platform
create a new site
go to /admin/commerce/config/demo and hit "wipe all content from this site"

**Comment by omega8cc** [comment] 2015-03-24 18:09
Duplicate of https://www.drupal.org/node/1859080

**Closed by omega8cc** 2015-03-24 18:09 UTC
