### ISSUE TITLE
"The drush command 'hosting-dispatch' could not be found." after server migration 

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#767] opened 2015-08-17 06:55 UTC
Hi,

after migrating a sever following the the instructions in MIGRATE.txt, I get an error running `# bash /var/xdrago/run-o1` on the target machine:

~~~
The drush command 'hosting-dispatch' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.              [error]
Drush was not able to start (bootstrap) the Drupal database.                                                                                                              [error]
...
~~~

It seems, that the the drupal root path of @hostmaster does not contain a Drupal installation:

~~~
$ls /data/disk/o1/aegir/distro/019 
cron.php  includes  index.php  install.php  misc  modules  profiles  sites  themes  update.php	xmlrpc.php
~~~

Any ideas what could have gone wrong during the migration?  
How can I fix it? 

The sites of the instance are running btw, but I cannot add or change sites.

Any help is appreciated.

Configuration Files
https://gist.github.com/luxio/8f33e92d1ea8f4a73016

**Comment by omega8cc** [comment] 2015-08-17 12:49
This is a duplicate of #763 -- please follow up there.

**Closed by omega8cc** 2015-08-17 12:49 UTC
