### ISSUE TITLE
"barracuda up-stable" uninstalls MariaDB

### ISSUE THREAD

**Issue by chriscroome** [omega8cc/boa#697] opened 2015-04-29 17:15 UTC
"barracuda up-stable" uninstalls MariaDB because MariaDB version number is currently behind the Debian Wheezy version number.

The last lot of MySQL packages from Debian on Wheezy has resulted in this situation:

    apt-get dist-upgrade
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Calculating upgrade... Done
    The following packages will be REMOVED:
      libmariadbclient-dev libmariadbclient18 libmariadbd-dev mariadb-client-5.5
      mariadb-client-core-5.5 mariadb-server-5.5 mariadb-server-core-5.5
    The following packages will be upgraded:
      libmysqlclient18
    1 upgraded, 0 newly installed, 7 to remove and 0 not upgraded.
    Need to get 0 B/677 kB of archives.
    After this operation, 117 MB disk space will be freed.
    Do you want to continue [Y/n]? n

Things are better with upgrade:

    apt-get upgrade
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages have been kept back:
      libmysqlclient18
    0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

This issue should go away when a version number greater that the Debian one is released by MariaDB, if I'm following this correctly.

My concern is what a BOA upgrade will do, it won't do a dist-upgrade and uninstall MariaDB will it? 

Just checking before upgrading to BOA 2.4.2.

**Comment by omega8cc** [comment] 2015-04-29 19:12
BOA doesn't use `dist-upgrade` for normal upgrades, so there is no reason to be afraid.

**Comment by chriscroome** [comment] 2015-04-29 21:08
I'm afraid MariaDB did get uninstalled:

    BOA [21:49:09] ==> INFO: Running aptitude full-upgrade...
    ...
    BOA [21:53:22] ==> INFO: Restarting MariaDB server...
    BOA [21:53:32] ==> INFO: Upgrading MariaDB tables if necessary...
    BOA [21:54:33] ==> ALRT! MariaDB server not installed properly!
    BOA [21:54:33] ==> EXIT: We can't proceed and will exit now
    BOA [21:54:33] ==> Bye

So reinstalling it:

    aptitude install libmariadbclient-dev libmariadbclient18 libmariadbd-dev mariadb-client-5.5 mariadb-client-core-5.5 mariadb-server-5.5 mariadb-server-core-5.5
    The following NEW packages will be installed:
    ...
    The following actions will resolve these dependencies:
    
         Downgrade the following packages:                                                                                  
    1)     libmysqlclient18 [5.5.43-0+deb7u1 (now, oldstable, oldstable-proposed-updates) -> 5.5.42+maria-1~wheezy (<NULL>)]
    
    Accept this solution? [Y/n/q/?] y
    The following packages will be DOWNGRADED:
      libmysqlclient18 
    The following NEW packages will be installed:
      libmariadbclient-dev libmariadbclient18 libmariadbd-dev mariadb-client-5.5 mariadb-client-core-5.5 mariadb-server-5.5 mariadb-server-core-5.5 
    Need to get 34.5 MB of archives. After unpacking 117 MB will be used.
    Do you want to continue? [Y/n/?] y

**Comment by chriscroome** [comment] 2015-04-29 21:30
MariaDB is now reinstalled, the download servers for it are really slow, there is some more detail here https://tech.transitionnetwork.org/trac/ticket/844#comment:5

This issue remains:

    aptitude dist-upgrade
    The following packages will be upgraded: 
      libmysqlclient18 
    1 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    Need to get 0 B/677 kB of archives. After unpacking 3524 kB will be used.
    The following packages have unmet dependencies:
     libmariadbclient18 : Depends: libmysqlclient18 (= 5.5.42+maria-1~wheezy) but 5.5.43-0+deb7u1 is to be installed.
    The following actions will resolve these dependencies:
    
         Remove the following packages:
    1)     libmariadbclient-dev        
    2)     libmariadbclient18          
    3)     libmariadbd-dev             
    4)     mariadb-client-5.5          
    5)     mariadb-client-core-5.5     
    6)     mariadb-server-5.5          
    7)     mariadb-server-core-5.5     
    
    Accept this solution? [Y/n/q/?] q

    apt-get dist-upgrade
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Calculating upgrade... Done
    The following packages will be REMOVED:
      libmariadbclient-dev libmariadbclient18 libmariadbd-dev mariadb-client-5.5 mariadb-client-core-5.5 mariadb-server-5.5 mariadb-server-core-5.5
    The following packages will be upgraded:
      libmysqlclient18
    1 upgraded, 0 newly installed, 7 to remove and 0 not upgraded.
    Need to get 0 B/677 kB of archives.
    After this operation, 117 MB disk space will be freed.
    Do you want to continue [Y/n]? n
    Abort.

Perhaps the libmysqlclient18 package can be pinned for now or something?

**Comment by omega8cc** [comment] 2015-04-30 10:23
Hmm.. this is weird and we can't reproduce this problem on Debian/wheezy x86_64

You should never install anything manually to avoid conflicts.

Please provide required config files so we could investigate this further.

**Comment by omega8cc** [comment] 2015-04-30 10:26
This is how it looks like after standard barracuda upgrade from 2.4.1 to 2.4.2

```
quad:~# aptitude search libmysqlclient
p   libmysqlclient-dev                                            - MySQL database development files
v   libmysqlclient15-dev                                          -
i A libmysqlclient18                                              - MySQL database client library
quad:~#
```

```
quad:~# aptitude search maria
i   libmariadbclient-dev                                          - MariaDB database development files
i A libmariadbclient18                                            - MariaDB database client library
i   libmariadbd-dev                                               - MariaDB embedded database development files
p   maria                                                         - reachability analyzer for Algebraic System Nets
p   maria-doc                                                     - documentation of Maria
p   mariadb-client                                                - MariaDB database client (metapackage depending on the latest version)
i   mariadb-client-5.5                                            - MariaDB database client binaries
i A mariadb-client-core-5.5                                       - MariaDB database core client binaries
i A mariadb-common                                                - MariaDB database common files (e.g. /etc/mysql/conf.d/mariadb.cnf)
p   mariadb-galera-server                                         - MariaDB database server with Galera cluster (metapackage depending on th
p   mariadb-galera-server-5.5                                     - MariaDB database server with Galera cluster binaries
p   mariadb-galera-test                                           - MariaDB database regression test suite (metapackage depending on the lat
p   mariadb-galera-test-5.5                                       - MariaDB database regression test suite
p   mariadb-server                                                - MariaDB database server (metapackage depending on the latest version)
i   mariadb-server-5.5                                            - MariaDB database server binaries
i A mariadb-server-core-5.5                                       - MariaDB database core server files
p   mariadb-test                                                  - MariaDB database regression test suite (metapackage depending on the lat
p   mariadb-test-5.5                                              - MariaDB database regression test suite
quad:~#
```

**Comment by omega8cc** [comment] 2015-04-30 10:27
Please read and follow https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt or your reports will be ignored.

**Comment by omega8cc** [comment] 2015-04-30 10:30
Again: BOA **doesn't** run `dist-upgrade` on standard upgrade, so I have no idea how you have got to this point.

**Comment by chriscroome** [comment] 2015-04-30 15:14
I don't know how it got to this point, I'm not aware of anything that has been manually installed that could cause conflicts.

The only thing I can think of that might be different from your test server is the `/etc/apt/apt.conf` file, this was edited to change "stable" to "wheezy" after Jessie came out due to an issue that was causing, it now looks like this:

    //
    //http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=638024
    //
    
    APT::Default-Release "wheezy" ;

The `/etc/apt/sources.list` looks like this:

    ## MAIN REPOSITORIES
    deb http://ftp.debian.org/debian/ wheezy main contrib non-free
    deb-src http://ftp.debian.org/debian/ wheezy main contrib non-free
    
    ## MAJOR BUG FIX UPDATES produced after the final release
    deb http://ftp.debian.org/debian/ wheezy-updates main
    deb-src http://ftp.debian.org/debian/ wheezy-updates main
    
    ## DEBIAN SECURITY UPDATES
    deb http://security.debian.org/ wheezy/updates main contrib non-free
    deb-src http://security.debian.org/ wheezy/updates main contrib non-free
    
    ## DEBIAN PROPOSED UPDATES
    deb http://ftp.debian.org/debian/ wheezy-proposed-updates main

The `/etc/apt/sources.list.d/dotdeb.list` (from when BOA used php from dotdeb) has every line commented out, `/etc/apt/sources.list.d/mariadb.list` contains:

    ## MariaDB APT Repository
    deb http://ftp.osuosl.org/pub/mariadb/repo/5.5/debian wheezy main
    deb-src http://ftp.osuosl.org/pub/mariadb/repo/5.5/debian wheezy main

And `/etc/apt/sources.list.d/newrelic.list` also has everything commented out that after a trial the use of newrelic was never continued.

The other files you wanted to see:

* https://tech.transitionnetwork.org/trac/attachment/ticket/844/tn.octopus.cnf
* https://tech.transitionnetwork.org/trac/attachment/ticket/844/barracuda.cnf
* https://tech.transitionnetwork.org/trac/attachment/ticket/844/octopus_log.txt
* https://tech.transitionnetwork.org/trac/attachment/ticket/844/barracuda_log.txt

Running the aptitude commands you ran above on the server:

    aptitude search libmysqlclient
    p   libmysqlclient-dev                                     - MySQL database development files
    v   libmysqlclient15-dev                                   -
    id  libmysqlclient16                                       - MySQL database client library
    i A libmysqlclient18                                       - MySQL database client library

    aptitude search maria
    i   libmariadbclient-dev                                   - MariaDB database development files
    i   libmariadbclient18                                     - MariaDB database client library
    i   libmariadbd-dev                                        - MariaDB embedded database development files
    p   maria                                                  - reachability analyzer for Algebraic System Nets
    p   maria-doc                                              - documentation of Maria
    p   mariadb-client                                         - MariaDB database client (metapackage depending on the latest vers
    i   mariadb-client-5.5                                     - MariaDB database client binaries
    i   mariadb-client-core-5.5                                - MariaDB database core client binaries
    i   mariadb-common                                         - MariaDB database common files (e.g. /etc/mysql/conf.d/mariadb.cnf
    p   mariadb-galera-server                                  - MariaDB database server with Galera cluster (metapackage dependin
    p   mariadb-galera-server-5.5                              - MariaDB database server with Galera cluster binaries
    p   mariadb-galera-test                                    - MariaDB database regression test suite (metapackage depending on
    p   mariadb-galera-test-5.5                                - MariaDB database regression test suite
    p   mariadb-server                                         - MariaDB database server (metapackage depending on the latest vers
    i   mariadb-server-5.5                                     - MariaDB database server binaries
    i   mariadb-server-core-5.5                                - MariaDB database core server files
    p   mariadb-test                                           - MariaDB database regression test suite (metapackage depending on
    p   mariadb-test-5.5                                       - MariaDB database regression test suite

**Comment by omega8cc** [comment] 2015-04-30 15:23
You should never modify apt files like this. We don't support systems where essential packages may be modified or go out of sync because you are introducing manual changes BOA doesn't control. I'm going to close this ticket.

**Closed by omega8cc** 2015-04-30 15:23 UTC
Labels: status - cannot reproduce, status - needs feedback, type - bug report

**Comment by omega8cc** [comment] 2015-04-30 15:26
Also, we don't support things like this:

`_STRICT_BIN_PERMISSIONS=NO`

This variable will be removed and forced anyway in the future.

**Comment by omega8cc** [comment] 2015-04-30 15:28
I suppose it is in fact a result of running _SQUEEZE_TO_WHEEZY=YES before and further apt modifications. This doesn't happen on systems installed in Wheezy. Using _SQUEEZE_TO_WHEEZY is deprecated. We recommend to migrate to clean Wheezy instead.

**Comment by omega8cc** [comment] 2015-04-30 15:29
Please check also: https://github.com/omega8cc/boa/issues/627#issuecomment-89672715

**Comment by omega8cc** [comment] 2015-04-30 15:31
To sum this up. Systems upgraded from Squeeze to Wheezy may experience issues caused by Debian itself, depending on various host specific differences.

**Comment by omega8cc** [comment] 2015-04-30 15:35
We have used the `xboa` migration on all our machines recently, mainly because we had to replace all hardware and locations, but it was also a good test and we recommend this workflow for major system upgrades to avoid bad surprises which could be a result of regressions introduced in newer Debian versions (it worked before for Lenny and Squeeze for us, though).

**Comment by chriscroome** [comment] 2015-05-01 08:54
The upgrade from Squeeze to Wheezy was done 18 months ago and the variable `#_SQUEEZE_TO_WHEEZY=YES` was commented out after [the upgrade](https://trac.transitionnetwork.org/trac/ticket/535#comment:20) (which, incidentally, failed using BOA scripts and [had to be done manually](https://trac.transitionnetwork.org/trac/ticket/535#comment:23)) but in any case that has now been changed to `#_SQUEEZE_TO_WHEEZY=NO` and also `_STRICT_BIN_PERMISSIONS=YES` has been changed.

I don't know which occurrence of `dist-upgrade` in the BOA scripts might have caused the problem, but it does appear [twice](https://github.com/omega8cc/boa/search?q=dist-upgrade), in `aegir/patches/nik.patch` and `lib/functions/system.sh.inc` .

In any event [MariaDB 5.5.43 now available](http://lists.askmonty.org/pipermail/announce/2015-May/000089.html) so this solves the issue.

**Comment by omega8cc** [comment] 2015-05-01 09:22
Please read the code closely. The `dist-upgrade` is used only when either `_LENNY_TO_SQUEEZE` or `_SQUEEZE_TO_WHEEZY` is set to `YES` **and** the current system version is either Lenny or Squeeze. Otherwise it is ignored altogether and never run.

**Comment by chriscroome** [comment] 2015-05-01 09:31
The system was Wheezy and the `_SQUEEZE_TO_WHEEZY` variable was commented out.

**Comment by omega8cc** [comment] 2015-05-01 10:35
In short, it was not possible that barracuda could run `dist-upgrade` on your system.

**Comment by chriscroome** [comment] 2015-05-01 10:56
The fact remains that `barracuda up-stable` uninstalled MariaDB on this server.

But there seems little point arguing about this since the new version of MariaDB has resolved this issue and I now know that if the Debian MySQL / MariaDB version numbers again have the situation where the Debian number is greater than the MariaDB one I'll not run any BOA scripts until a new version of MariaDB catches up with Debian.
