### ISSUE TITLE
impossible to install drupal 8 site 

### ISSUE THREAD

**Issue by yazzou** [omega8cc/boa#1200] opened 2017-08-30 06:37 UTC
Hello 
Here are boa info more details 
https://gist.github.com/yazzou/9dab158a0aa93c6b463a983cdbbb7486#file-boa-info-more

Whenever i try to install a drupal 8 site i got this error 

https://gist.github.com/yazzou/d2044c2e954252eb72f2b870eab15e93

**Comment by yaazkal** [comment] 2017-08-31 20:13
Hi, I'm not sure _how_ are you trying to install it, please note that D8 is not officially supported but you can include it as a platform as said [here](https://github.com/omega8cc/boa/blob/2bd8b136475170f7be85b1fdae82a75904dee29c/README.txt#L163)

Make sure that core and other related drupal directories/files are in the root of the platform, by now there is no support for drupal composer based project. Anyway you can follow #1116 and check if it works for you.

**Comment by omega8cc** [comment] 2017-09-07 22:01
Looks like a duplicate of #1184

**Closed** 2017-09-07 22:02 UTC
Labels: status - duplicate, type - question
