### ISSUE TITLE
RVM not installed correctly

### ISSUE THREAD

**Issue by danielgroen** [omega8cc/boa#1363] opened 2019-04-03 16:05 UTC
I've done a clean installation of BOA 4.0 on a Digital ocean droplet.
I've installed php 7.0.

Now that i just wanted to run gulp, bower ect, i needed to add 'CSS' to the XTRAS in .barracuda.conf, which i did. runned the 'barracuda up-head system' as usual. Aterwards i added the compass.info file and waited for 15 minutes.

After logging in again i typed: rvm all do gem install --conservative compass.
Now as o1.ftp, i see that rvm is loaded (rvm -v) but i can not use npm by 'npm install gulp -g', node -v, does not work and the gems are not installed because the gems folder in .rvm/gems is empty.

Am i doing somewhat wrong or is there something changed?
Allthough i am using boa 4, i also got this problem on the latest boa 3 which i tested two weeks early.

[UPDATE]: i've got the same problem on boa 3.2 on debian 8
When i type: ls when o1.ftp i also get the following message:
grep: /home/o1.ftp/.rvm/environments/default: No such file or directory
![Schermafdruk van 2019-04-04 17-14-29](https://user-images.githubusercontent.com/6578052/55567033-3062b280-56fd-11e9-91d6-12c07b5384fb.png)

**Comment by omega8cc** [comment] 2019-04-08 20:25
Once you add CSS keyword, but before running barracuda upgrade, you need to remove leftovers:

`rm -f /var/xdrago/log/compass*`

Only then the dependencies will be installed properly and enabling RVM etc will work.

We should fix this annoying bug..

**Comment by aanjaneyam** [comment] 2019-04-26 15:32
I have similar problem. I am following error:
`c1.ftp:~$ rvm --version `
`grep: /home/c1.ftp/.rvm/environments/default: No such file or directory`
`rvm 1.29.7 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]`

`c1.ftp:~$ rvm all do gem install --conservative compass`
`grep: /home/c1.ftp/.rvm/environments/default: No such file or directory`

I then, according to above advice, did the following steps:

1) deleted ~/static/control/compass.info and waited 20 minutes.
2) Ran the command `rm -f /var/xdrago/log/compass*` and waited 15 minutes.
3) ran `barracuda -up-head system` and waited for another 15 minutes after the command completion.
4) added compass.info file `touch ~/static/control/compass.info` and waited for 20 minutes.

However, I still get the above error and cannot run rvm commands as it complains about default environment. As above, running rvm --version gives the rvm version installed but along with grep: /home/c1.ftp/.rvm/environments/default: No such file or directory

I use c1 instead of o1 as octopus user.

**Comment by aanjaneyam** [comment] 2019-04-26 15:33
Upon removing /var/xdrago/log/compass* and running barracuda upgrade I saw the packages RVM being reinstalled on the output of barracuda upgrade command..

**Comment by omega8cc** [comment] 2019-05-05 03:29
We have tried to reproduce the problem on Digital Ocean and we couldn't. It works when you follow the docs:

All we did was:

1. Install BOA head
2. Reboot
3. Add `CSS` to `_XTRAS_LIST` in `/root/.barracuda.cnf`
4. Run barracuda upgrade
5. Switch to `o1.ftp`
6. `touch ~/static/control/compass.info`
7. Wait until RVM installation is complete
8. Log out and log in again and install compass and gulp

It works:

```
o1.ftp:~$ rvm -v
rvm 1.29.7 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
o1.ftp:~$ compass --version
Compass 1.0.3 (Polaris)
Copyright (c) 2008-2019 Chris Eppstein
Released under the MIT License.
Compass is charityware.
Please make a tax deductable donation for a worthy cause: http://umdf.org/compass
o1.ftp:~$ gulp -v
CLI version: 2.2.0
Local version: 4.0.1
o1.ftp:~$
```

Please triple check that `~/static/control/compass.info` actually exists..

**Comment by omega8cc** [comment] 2019-05-05 03:30
@danielgroen @aanjaneyam See above.

**Comment by omega8cc** [comment] 2019-05-05 03:35
Maybe you have too small droplet? Not sure. The compilation takes a long time if you don't have at least 2 CPU and 4 GB RAM.

**Comment by aanjaneyam** [comment] 2019-05-05 13:21
I have 2 CPU and 4GB RAM and I followed the steps stated above. I also checked that ~/static/control/compass.info actually exists. Anyways I will rebuild the Digital ocean debian 9 server and reinstall BOA and rvm following the steps stated above to see if it works.  Is there anything to do with firewall. Well I have ll the outgoing ports open and incoming ports ssh, http, https and webmin open.

**Comment by omega8cc** [comment] 2019-05-05 13:50
@aanjaneyam We have tested this always on a blank default Debian 9 VPS, nothing custom, default BOA install. It worked on all attempts..

**Comment by aanjaneyam** [comment] 2019-05-05 14:04
Hi. I am reinstalling right now after a server rebuild on DO. Let's see. This time I am using o1 as system user instead of c1. Which barracuda upgrade command should we run after initial BOA install, reboot and adding CSS to XTRAS_LIST (I also plan to add WMN and GIT) - `barracuda up-head` or `barracuda up-head system`.

**Comment by aanjaneyam** [comment] 2019-05-05 14:08
Strange now the installation is stuck at 

BOA [13:51:28] ==> INFO: Retrieving F1656F24C74CD1D8 key..
BOA [13:53:01] ==> INFO: Retrieving F1656F24C74CD1D8 key..
BOA [13:54:33] ==> INFO: Retrieving F1656F24C74CD1D8 key..
BOA [13:56:06] ==> INFO: Retrieving F1656F24C74CD1D8 key..
BOA [13:57:38] ==> INFO: Retrieving F1656F24C74CD1D8 key..
BOA [13:59:10] ==> INFO: Retrieving F1656F24C74CD1D8 key..
BOA [14:00:42] ==> INFO: Retrieving F1656F24C74CD1D8 key..
BOA [14:01:05] ==> INFO: Retrieving F1656F24C74CD1D8 key..
BOA [14:01:35] ==> INFO: Retrieving F1656F24C74CD1D8 key..
BOA [14:03:07] ==> INFO: Retrieving F1656F24C74CD1D8 key..
BOA [14:04:40] ==> INFO: Retrieving F1656F24C74CD1D8 key..
BOA [14:06:12] ==> INFO: Retrieving F1656F24C74CD1D8 key..

**Comment by omega8cc** [comment] 2019-05-05 14:09
What is your VPS data centre location? It seems to have connectivity issues?

**Comment by omega8cc** [comment] 2019-05-05 14:10
This happened before but after adding some extra checks we never experienced it again: https://github.com/omega8cc/boa/issues/1323

**Comment by aanjaneyam** [comment] 2019-05-05 14:12
My VPS is in London data centre.

**Comment by omega8cc** [comment] 2019-05-05 14:14
We are testing in Frankfurt:

```
v1:~# hostname
v1.do.de.boa.io
v1:~# gpg2 --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "F1656F24C74CD1D8"
gpg: key F1656F24C74CD1D8: 6 signatures not checked due to missing keys
gpg: key F1656F24C74CD1D8: "MariaDB Signing Key <signing-key@mariadb.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
v1:~#
```

**Comment by aanjaneyam** [comment] 2019-05-05 14:17
Should I run `gpg2 --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "F1656F24C74CD1D8"` before trying to reinstall BOA again. Obvious I will have to rebuild the server again. What else could I do as not it changes from data centre to data centre too.

**Comment by omega8cc** [comment] 2019-05-05 14:18
Could be a temporary connectivity issue. We could use our own mirrors to download keys, if that helps, perhaps.

**Comment by omega8cc** [comment] 2019-05-05 14:20
Does it work on command line for you? if yes, just try to run the installation again. remember to add add in .baracuda.cnf

###
### Use YES to force installing everything
### from sources again, even if there are
### no updates available.
###
_FULL_FORCE_REINSTALL=YES

**Comment by aanjaneyam** [comment] 2019-05-05 14:25
Well as said above it has proceeded to further installation steps. Hopefully the key was successfully retrieved and install will be successful. I will let the the install complete.

**Comment by aanjaneyam** [comment] 2019-05-05 14:49
What is the preferred barracuda upgrade command after initia BOA install and reboot (after adding CSS symbol) `barracuda up-head` or `barracuda up-head system`.

**Comment by omega8cc** [comment] 2019-05-05 14:57
It doesn't matter, we have run just `barracuda up-head`

**Comment by aanjaneyam** [comment] 2019-05-05 15:57
Well I finished initial BOA install; reboot after waiting two minutes; run barracuda upgrade. 
Then switch to o1.ftp `su - o1.ftp`
`o1.ftp:~$ touch ~/static/control/compass.info`
`touch: cannot touch '/home/o1.ftp/static/control/compass.info': Permission denied`

This has not happened before looks like the ~/static/control is owned by root so cannot touch compass.info as o1.ftp. Should I have waited a bit more before rebooting after the BOA head install completed so that permissions could have been fixed.

**Comment by aanjaneyam** [comment] 2019-05-05 19:12
Any clues on why ~/static/control/ has root privileges tush preventing creation of compass.info file. This has happened for the first time.

**Comment by omega8cc** [comment] 2019-05-06 00:24
You have root access, you can fix any permissions and ownership you need.

This should be already fixed meanwhile..

**Comment by aanjaneyam** [comment] 2019-05-06 13:04
No it hasn't fixed already. I just checked it. I will change the ownership manually but I always thought that BOA does lots of things automatically by it's permission fix system and never had such an issue so thought something which BOA does with permissions is not happening.

**Comment by omega8cc** [comment] 2019-05-06 15:29
It was a bug we have fixed (I think) in https://github.com/omega8cc/boa/commit/20eb3e070404ccfb3d1b29b40fb9a630c3f257e8 but since the auto-fix depends on control files it creates, your system couldn't fix that until we increase the serial number in the control files filenames. We shall try again on a fresh Octopus instance I guess.

**Comment by omega8cc** [comment] 2019-05-06 15:53
@aanjaneyam  Just checked on a fresh install, and it's indeed fixed:

```
root@v1:/data/disk/o7t/static# ll
total 12K
drwxr-sr-x 2 o7t.ftp users 4.0K May  6 15:39 control/
-rw-r--r-- 1 root    users    6 May  6 15:39 EMPTY.txt
-rw-r--r-- 1 o7t     users  745 May  6 15:39 o7t.id_rsa.pub
```

**Comment by aanjaneyam** [comment] 2019-05-06 16:18
Below is what I have on a fresh install just finished few minutes ago :

`ls -la /data/disk/o1/static/control/`
`total 16`
`drwxr-sr-x 2 o1.ftp users 4096 May  6 16:10 .`
`drwxrwsr-x 3 o1     users 4096 May  6 16:10 ..`
`-rw-r--r-- 1 root   users    4 May  6 16:10 cli.info`
`-rw-r--r-- 1 root   users    4 May  6 16:10 fpm.info`
looks like cli.info and fpm.info are still owned by root but yes the ownership of the directory (control) itself is fixed. Should cli.info and fpm.info be owned by root.

**Comment by aanjaneyam** [comment] 2019-05-06 16:23
I see it now seems to have fixed itself after few minutes.

`ls -la /data/disk/o1/static/control/`
`total 32`
`drwxr-sr-x 2 o1.ftp users 4096 May  6 16:13 .`
`drwxrwsr-x 3 o1     users 4096 May  6 16:10 ..`
`-rw-r--r-- 1 o1.ftp users    4 May  6 16:10 cli.info`
`-rw-r--r-- 1 root   users    3 May  6 16:13 .ctrl.401prodQ1.pid`
`-rw-r--r-- 1 o1.ftp users    4 May  6 16:10 fpm.info`
`-rw-r--r-- 1 o1.ftp users 8914 May  6 05:57 README.txt`

I will now reboot and then add the CSS, WMN and GIT symbols and run barrracuda up-head system. Fingers crossed, hopefully this time I will get a fully working system with rvm and NPM

**Comment by omega8cc** [comment] 2019-05-06 16:23
@aanjaneyam Thanks for the heads up. You are right. It's still another bug/regression to fix.

```
root@v1:/data/disk/o7t/static/control# ll
total 8.0K
-rw-r--r-- 1 root users 4 May  6 15:39 cli.info
-rw-r--r-- 1 root users 4 May  6 15:39 fpm.info
```

**Comment by omega8cc** [comment] 2019-05-06 16:24
@aanjaneyam No need to run `up-head` -- use `up-stable` now the 4.0.1 is released.

**Comment by aanjaneyam** [comment] 2019-05-06 17:45
No the rvm problem remains. I followed every recommended steps , triple checked everything but still:
1) start new droplet in london region using Debian 9.7 x64 base image on 2cpu 4gb ram instance.
2) install BOA stable 4.01
3) after the initial install finishes - change passwords for master and satellite instance aegir panel using one time link.
4) reboot the droplet with reboot command on terminal.
5) edit .barracuda.cnf and add CSS WMN and GIT to XTRAS_LIST.
6) run `barracuda up-stable system`
7) after the upgrade completes switch to o1.ftp with `su - o1.ftp`
8) `touch ~/static/control/compass.info`
9) wait for about 35 minutes.
10) Log out and log back in 
11) test rvm
`o1.ftp:~$ rvm --version`
`grep: /home/o1.ftp/.rvm/environments/default: No such file or directory`
`rvm 1.29.7 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]`

`o1.ftp:~$ rvm all do gem install --conservative compass`
`grep: /home/o1.ftp/.rvm/environments/default: No such file or directory`
`o1.ftp:~$ compass --version`
`grep: /home/o1.ftp/.rvm/environments/default: No such file or directory`
`/bin/dash: 1: compass: not found`

I don't know what is going on. what is this line `grep: /home/o1.ftp/.rvm/environments/default: No such file or directory` . Why is it complaining about default environment? Is it a problem with shell environment. 

OR is it the debian 9 base image which has some problem only in London data centre.

**Comment by aanjaneyam** [comment] 2019-05-07 08:43
Why I am not able to run the rvm and npm commands  despite following everything recommended and triple checking. I also changed the provider from Linode to Digital ocean. Do I provide any log files that may help you see the problem.

**Comment by omega8cc** [comment] 2019-05-07 09:33
@aanjaneyam  Please try to strictly follow our testing steps and don’t add any extras on the first upgrade beyond CSS. It’s the only difference apparently. We haven’t tested WMN for years and since it may install conflicting dependencies who knows what happens then.. once we have this confirmed we can try to debug further. Also make sure the RVM etc installs are actually finished with `ps axf` command.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aanjaneyam** [comment] 2019-05-07 10:07
What should I do now? rebuild the server and and reinstall BOA stable or is there an easier way. By the way I have also tried with only CSS symbol(without WMN and GIT) and the problem was same. I can try again if you think so that webmin and git are causing the problem. I am not sure what problems webmin could cause.

**Comment by omega8cc** [comment] 2019-05-07 16:32
We will try to test it again in London DO, we will see. Really weird we couldn't reproduce the problem anywhere before.

**Comment by aanjaneyam** [comment] 2019-05-07 19:28
I am not sure too. I believe we should also think about key servers too as on a fresh attempt my barracuda upgrade after reboot got infinitely stuck on retrieving key  for RVM. I am now in the process of running `rm -f /var/xdrago/log/compass*` and retrying upgrade with CSS symbol.

**Comment by omega8cc** [comment] 2019-05-07 19:34
We have tried to put as much as possible on our mirrors to minimize side effects of remote servers availability, so perhaps should do the same to these keys..

**Comment by omega8cc** [comment] 2019-05-07 20:24
We are now using our mirrors for these keys. We still use remote keys for MariaDB and Percona, but they never caused any issues, so not changing it beyond RVM for now.

**Comment by aanjaneyam** [comment] 2019-05-08 00:18
No. I reinstalled BOA on a fresh rebuilt server, rebooted, added only CSS symbol this time to .barracuda.cnf and ran barracuda upgrade -> switch to o1.ftp, touch the compass.info and wait 35 minutes -> log out and log back in and test the following commands:

`o1.ftp:~$ rvm --version`
`grep: /home/o1.ftp/.rvm/environments/default: No such file or directory`
`rvm 1.29.7 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]`

`o1.ftp:~$ rvm all do gem install --conservative compass`
`grep: /home/o1.ftp/.rvm/environments/default: No such file or directory`
`o1.ftp:~$ compass --version`
`grep: /home/o1.ftp/.rvm/environments/default: No such file or directory`
`/bin/dash: 1: compass: not found`
`o1.ftp:~$ npm`
`grep: /home/o1.ftp/.rvm/environments/default: No such file or directory`
`/bin/dash: 1: npm: not found`
`o1.ftp:~$ `

So it is not the problem with webmin control panel. I am attaching the output of ps axf command.

[ps-axf.txt](https://github.com/omega8cc/boa/files/3154949/ps-axf.txt)

**Comment by omega8cc** [comment] 2019-05-08 15:15
We have managed to reproduce this on Linode VPS in London. Interesting.. debugging now.

**Comment by aanjaneyam** [comment] 2019-05-08 19:55
Oh thanks! That's great news.

**Comment by omega8cc** [comment] 2019-05-09 02:45
@aanjaneyam The problem should be solved now (in HEAD). There were actually a few problems, and we could experience them only on Linode in London. Anyway, hopefully no more surprises. We have also decided to add CSS to the default installation.

**Comment by omega8cc** [comment] 2019-05-09 02:49
We have also confirmed that 1 CPU and 2 GB RAM is still enough to make it work, just a bit slow, especially on Linode.

**Comment by aanjaneyam** [comment] 2019-05-09 10:07
Well I will give it a go. I am surprised that you were not able to replicate on DO London but only on Linode.

**Comment by aanjaneyam** [comment] 2019-05-09 10:54
@omega8cc so you mean I should freshly install the new HEAD for production server and upgrade it to stable when 4.0.2 comes out and then continue from there.

**Comment by omega8cc** [comment] 2019-05-09 22:20
@aanjaneyam We haven't tested on DO/London, only DO other locations and Linode/London.

You don't need to start from scratch, just upgrade barracuda to head -- it should work too.

However, Linode in London is pretty weird.. just a few minutes ago a stable install failed to build PHP for unknown reasons. So who knows if the ghost we are chasing actually has anything to do with BOA, if everything worked just fine for us many times on DO in Frankfurt.

**Comment by aanjaneyam** [comment] 2019-05-10 10:00
For me, the rvm installation problem was present in each and every install on both DO and Linode in London. However, I did not experience the PHP building problem on either of them. Strange. What could be wrong in London data centres of both provider. We may be able to open a ticket with them.

**Comment by aanjaneyam** [comment] 2019-05-10 12:50
Upon running barracuda up-head I receive a ruby install failed error:
```
Do you want to install Ruby with RVM? [Y/n] y
BOA [12:47:08] ==> INFO: Running Ruby with RVM install...
BOA [12:47:58] ==> WARN: Ruby 2.6.0 install failed!
```

**Comment by aanjaneyam** [comment] 2019-05-10 13:13
Looks like I would have to start from scratch to see if things work as upgrade from 4.0.1 stable to 4.0.2-dev doesn't seem to resolve the issue.

**Comment by omega8cc** [comment] 2019-05-10 13:43
You can fix this manually once at least RVM is installed as root:

```
source /etc/profile.d/rvm.sh
rvm install 2.6.0
rvm use 2.6.0 --default
```

**Comment by aanjaneyam** [comment] 2019-05-10 13:45
The above manual commands are be run as root or o1.ftp?

**Comment by omega8cc** [comment] 2019-05-10 13:50
Root. Once completed you can start using compass.info in the limited shell accounts.

**Comment by omega8cc** [comment] 2019-05-10 13:51
Now head install fails for us. Not sure what is going on in London, but we are breaking head trying to debug this at the moment.

**Comment by aanjaneyam** [comment] 2019-05-10 13:58
I am testing on DO London so see what happens.

**Comment by aanjaneyam** [comment] 2019-05-10 15:27
We the fresh HEAD install completed without errors. But rvm not found for o1.ftp
```
cws01:~# whoami 
root
cws01:~# which rvm
/usr/local/rvm/bin/rvm
cws01:~# su - o1.ftp
o1.ftp:~$ rvm --version
/bin/dash: 1: rvm: not found
o1.ftp:~$ rvm all do gem install --conservative compass
/bin/dash: 1: rvm: not found
o1.ftp:~$ 
o1.ftp:~$ npm --version
6.4.1
o1.ftp:~$ 
```
Looks like npm is installed but not rvm.

```
o1.ftp:~$ npm install -g grunt
/home/o1.ftp/.npm-packages/bin/grunt -> /home/o1.ftp/.npm-packages/lib/node_modules/grunt/bin/grunt
+ grunt@1.0.4
added 97 packages from 63 contributors in 4.675s
o1.ftp:~$ npm install -g gulp-cli
/home/o1.ftp/.npm-packages/bin/gulp -> /home/o1.ftp/.npm-packages/lib/node_modules/gulp-cli/bin/gulp.js
+ gulp-cli@2.2.0
added 236 packages from 157 contributors in 8.253s
o1.ftp:~$ 
````

**Comment by aanjaneyam** [comment] 2019-05-10 15:46
Though rvm for root was successfully installed by initial BOA HEAD install. But it is not available for o1.ftp
```
cws01:~# rvm --version
rvm 1.29.8 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
cws01:~# 
````

**Comment by aanjaneyam** [comment] 2019-05-13 09:30
I tried another time yesterday and the same result. RVM is installed for root but not available to o1.ftp. However NPM is available. What could be wrong?

**Comment by aanjaneyam** [comment] 2019-05-14 09:29
I am still stuck at rvm not available to o1.ftp as stated above. Any clues please as I need to get on to site development work.

**Comment by aanjaneyam** [comment] 2019-05-16 11:16
After having seen the commits of 15 may I tried fresh install again last night  but no help with rvm not found for o1.ftp.
```
o1.ftp:~$ rvm --version
/bin/dash: 1: rvm: not found
```

**Comment by aanjaneyam** [comment] 2019-05-16 15:44
I have tried a few more commands below and found that looks like things are installed but somehow due to some restrictions in shell or something else it seems that it is just the rvm command that is not available. I am saying this because before may of those commands were not working.

```
o1.ftp:~$ ll ~/.rvm/environments/
total 0
lrwxrwxrwx 1 o1.ftp users 41 May 16 10:00 default -> /home/o1.ftp/.rvm/environments/ruby-2.6.0
lrwxrwxrwx 1 o1.ftp users 45 May 16 10:00 ruby-2.6.0 -> /home/o1.ftp/.rvm/gems/ruby-2.6.0/environment
lrwxrwxrwx 1 o1.ftp users 52 May 16 10:00 ruby-2.6.0@global -> /home/o1.ftp/.rvm/gems/ruby-2.6.0@global/environment
```
```
o1.ftp:~$ gem-list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3)
minitest (5.9.0)
net-telnet (0.1.1)
power_assert (0.2.7)
psych (2.1.0)
rake (10.5.0)
rdoc (4.2.1)
test-unit (3.1.7)
```

```
o1.ftp:~$ gem-environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2.1
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /home/o1.ftp/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.3
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/o1.ftp/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.3.0
     - /home/o1.ftp/.gem/ruby/2.3.0
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/2.3.0
     - /usr/share/rubygems-integration/all
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/local/games
     - /usr/games
     - /usr/local/bin
     - /opt/local/bin
```

**Comment by omega8cc** [comment] 2019-05-16 17:54
This should be fixed in head now. Thanks @aanjaneyam for the helpful feedback!

**Comment by aanjaneyam** [comment] 2019-05-16 19:01
Thanks for your co-operation too @omega8cc ! Yes it indeed looks fixed now. Both the rvm and npm commands work and installs what they are asked to.

**Comment by omega8cc** [comment] 2019-05-16 21:55
Fantastic! Closing as fixed then!

**Closed by omega8cc** 2019-05-16 21:55 UTC
Labels: status - fixed, type - bug report
