### ISSUE TITLE
Changing the default upload_max_filesize

### ISSUE THREAD

**Issue by luxio** [omega8cc/boa#636] opened 2015-02-28 16:41 UTC
I have changed the maximum size for uploading files by changing the corresponding settings in 

* **/opt/php53/etc/php53.ini**  (max_execution_time, max_input_time, post_max_size, upload_max_filesize)
* **/opt/php53/etc/pool.d/www53.conf** (request_terminate_timeout)
* **/var/aegir/config/server_master/nginx.conf** (client_max_body_size)

Is there a way to prevent the override of these settings when updating boa?

**Comment by omega8cc** [comment] 2015-03-02 20:36
It is not configurable (yet), so these changes will be overwritten. We could also add `client_max_body_size` to the BOND script, which already allows to tune other related settings.

Currently only `request_terminate_timeout` is configurable via `_PHP_FPM_TIMEOUT`

**Comment by omega8cc** [comment] 2015-03-02 20:37
Also related: #559

**Comment by omega8cc** [comment] 2015-10-17 20:28
This is now a duplicate of #752 

There is also a clever solution: https://github.com/omega8cc/boa/issues/752#issuecomment-122467075

**Closed by omega8cc** 2015-10-17 20:28 UTC
Labels: status - needs work, type - feature request
