### ISSUE TITLE
Drupal 8 reports OPCode Caching is not enabled

### ISSUE THREAD

**Issue by bserem** [omega8cc/boa#1012] opened 2016-07-01 12:38 UTC
Drupal 8.1.x (I don't know about previous versions) on BOA reports that opcode is not enabled.

copy/paste from /admin/reports/status
```
PHP OPcode caching 	Not enabled
PHP OPcode caching can improve your site's performance considerably. It is highly recommended to have OPcache installed on your server.
```

This is from a BOA 3.1.1 installation (local or public, it is the same).
The makefile used to create the D8 platform is: https://raw.githubusercontent.com/drupalcampgr/boa-session/master/makefiles/D813.make (nothing fancy).
System is Debian 8.5.

**Comment by omega8cc** [comment] 2016-07-01 16:43
Duplicate of #847

**Closed by omega8cc** 2016-07-01 16:43 UTC
