### ISSUE TITLE
Clean system install with Stable or Head 4.3.1 does not complete

### ISSUE THREAD

**Issue by iaminawe** [omega8cc/boa#1598] opened 2021-11-10 01:05 UTC
Using Debian Stretch fresh instance

If I install stable - I end up with Percona missing Key loop
If I install head  - It ends up hanging after PHP 7.4 has installed - Part 3/3

Neither of these gives me a workable Aegir instance

Can anyone install this fresh without issues at the moment?

Thanks in advance for any attention this can be given - I am on week 2 of trying different things and have not been able to get anything to work

**Comment by EdNett** [comment] 2021-11-11 16:27
we can't get any boa head to install on debian 9 either as of nov 11 2021

**Comment by lexsoft00** [comment] 2021-11-26 19:35
Also having issues on a clean Debian 10 install. It's stuck at:

```
BOA [19:15:41] ==> INFO: Building PHP 7.3.33 from sources, please wait...
BOA [19:15:46] ==> INFO: Building PHP 7.3.33 part 1/3
BOA [19:15:49] ==> INFO: Building PHP 7.3.33 part 2/3
BOA [19:16:32] ==> INFO: Building PHP 7.3.33 part 3/3
```

Is there a way to see the install in a more verbose way? I can't tell why is not moving with the update, does it expect some input from me maybe that I don't see?

**Comment by lexsoft00** [comment] 2021-12-02 11:00
Percona seems to fail:
```
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1565: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1567: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1570: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1587: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1589: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1591: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1593: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1595: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1597: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1600: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1602: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1604: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1614: mysqladmin: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1616: mysqladmin: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1707: /etc/mysql/skip-name-resolve.txt: No such file or directory
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1721: mysqladmin: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1723: mysqladmin: command not found
```

**Comment by lexsoft00** [comment] 2021-12-02 11:27
```
BOA [11:21:33] ==> INFO: Installing Percona...
BOA [11:21:43] ==> INFO: Retrieving 8507EFA5 key..
E: Unable to locate package percona-release
BOA [11:21:55] ==> INFO: Installing Percona 5.7 in Debian/buster
BOA [11:23:31] ==> INFO: Running Percona tables fix, check and upgrade...
usermod: user 'mysql' does not exist
BOA [11:23:31] ==> INFO: Generating random password for Percona
BOA [11:23:31] ==> INFO: New Percona root password in /root/.my.pass.txt
BOA [11:23:31] ==> INFO: Percona final setup
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1565: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1567: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1570: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1587: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1589: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1591: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1593: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1595: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1597: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1600: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1602: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1604: mysql: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1614: mysqladmin: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1616: mysqladmin: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1707: /etc/mysql/skip-name-resolve.txt: No such file or directory
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1721: mysqladmin: command not found
/opt/tmp/boa/lib/functions/sql.sh.inc: line 1723: mysqladmin: command not found
BOA [11:23:31] ==> INFO: Restarting Percona server...

```

**Comment by omega8cc** [comment] 2021-12-13 21:20
We can't reproduce this and are installing new instances almost daily.

Please provide more details on your host if you can't run required `boa info more` https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by lexsoft00** [comment] 2021-12-14 09:37
[OHV VPS](https://www.ovhcloud.com/en/vps/) 8v cpu 16GB RAM Debian9
https://gist.githubusercontent.com/lexsoft00/70c03500c14435d6a4e276db828b0de4/raw/4edbcc6f018ab07d46ca0b32435ebf844cb8ff97/gistfile1.txt

**Comment by omega8cc** [comment] 2021-12-16 01:43
Closing as duplicate of https://github.com/omega8cc/boa/issues/1609

**Closed by omega8cc** 2021-12-16 01:43 UTC
Labels: type - bug report, status - needs feedback
