### ISSUE TITLE
install process is stuck

### ISSUE THREAD

**Issue by albertollamaso** [omega8cc/boa#1580] opened 2021-07-12 18:29 UTC
I am running 
```
apt-get update -y
cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
boa in-stable public mytest.mydomain.com xxxxxxx@gmail.com o1

```

An keep stuck at the beginning in:
```
BOA [18:22:25] ==> NOTE: after boa completes initial installation
BOA [18:22:25] ==> NOTE: in order to remove unused systemd packages!

BOA [18:22:39] ==> INFO: Installing more basic tools now, please wait...
BOA [18:23:16] ==> INFO: DNS test: OK
 
BOA [18:23:16] ==> INSTALL START -> checkpoint: 

    * Your email address is XXXXXX@gmail.com (REDACTED)
    * Your IP address is XX.XX.XX.XX (REDACTED)
    * Your hostname is mytest.mydomain.com
 
BOA [18:23:16] ==> INFO: Installing extra Drush versions...
BOA [18:23:25] ==> INFO: Running system packages update...
BOA [18:23:42] ==> INFO: Installing required libraries and tools, please wait...
BOA [18:24:55] ==> INFO: Installing Percona...
BOA [18:25:05] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:25:11] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:25:16] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:25:21] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:25:27] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:25:32] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:25:37] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:25:42] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:25:48] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:25:53] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:25:58] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:26:04] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:26:09] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:26:14] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:26:19] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:26:25] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:26:30] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:26:35] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:26:40] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:26:46] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:26:51] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:26:56] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:27:01] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:27:07] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:27:12] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:27:17] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:27:23] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:27:28] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:27:33] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:27:39] ==> INFO: Retrieving 8507EFA5 key..
BOA [18:27:44] ==> INFO: Retrieving 8507EFA5 key..

```

**Comment by Juc1** [comment] 2021-07-17 21:59
@albertollamaso this question was asked on https://gitter.im/omega8cc/boa where @omega8cc replied "use head" so
$ boa in-head public mytest.mydomain.com xxxxxxx@gmail.com o1

**Comment by Juc1** [comment] 2021-08-10 11:37
update - I am having the same problem today trying to install head - so it seems that using head does not fix this problem.

**Comment by jcandan** [comment] 2021-08-10 21:43
I am also experiencing this on a fresh Debian 9 Digital Ocean base droplet.

**Comment by jcandan** [comment] 2021-08-10 21:46
Though, as a point of difference, I did not run `apt-get update -y` prior to `bash BOA.sh.tx` as instructed in point 4 in [INSTALL.md](https://github.com/omega8cc/boa/blob/master/docs/INSTALL.txt):

> Don't run any system updates before running Barracuda installer. You should use vanilla system.

**Comment by jcandan** [comment] 2021-08-10 22:27
Tried `in-head` this time. Seems I made it past this hurdle.

**Comment by Juc1** [comment] 2021-08-10 22:27
@jcandan same as me - Digital Ocean, fresh vanilla Debian 9, no system updates.

Putty log below...


```

Using username "root".
Authenticating with public key "rsa-key-08122015"
Linux aldgate 4.9.0-15-amd64 #1 SMP Debian 4.9.258-1 (2021-03-08) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@aldgate:~# cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt

BOA Meta Installer setup completed
Please check INSTALL.txt and UPGRADE.txt at http://bit.ly/boa-docs
Bye


The system is ready for BOA installation!

We will start screen session for you in 15 seconds
to avoid problems with dropped SSH connections
during BOA stack installation, which may take up to
30-60 minutes, depending on your server speed.

If your connection will drop, simply log in again
and re-attach your session with 'screen -R' command.

Please wait a moment until this message disappears.

Enjoy!

root@aldgate:~# boa in-head public aldgate.example.com hello@example.com o1
 
BOA [09:26:41] ==> Skynet Agent v.BOA-4.1.4-dev welcomes you aboard!
 
BOA [09:26:44] ==> INFO: NORMAL INIT
BOA [09:26:45] ==> INFO: Public Setup Mode Active
BOA [09:26:45] ==> INFO: Creating your /root/.barracuda.cnf config file
BOA [09:26:49] ==> VIRT: This system is supported: Linux KVM guest
 
BOA [09:26:49] ==> Aegir on aldgate Debian/stretch x86_64 PHP 7.4
 
BOA [09:26:49] ==> INFO: Installing some basic tools now, please wait...
BOA [09:26:59] ==> INFO: Installing sysvinit-core on Debian stretch...

BOA [09:27:07] ==> NOTE: Please reboot and run 'barracuda up-head system'
BOA [09:27:07] ==> NOTE: after boa completes initial installation
BOA [09:27:07] ==> NOTE: in order to remove unused systemd packages!

BOA [09:27:22] ==> INFO: Installing more basic tools now, please wait...
BOA [09:27:47] ==> INFO: DNS test: OK
 
BOA [09:27:47] ==> INSTALL START -> checkpoint: 

    * Your email address is hello@example.com
    * Your IP address is 111.222.33.44
    * Your hostname is aldgate.example.com
 
BOA [09:27:47] ==> INFO: Installing supported Drush versions...
BOA [09:27:47] ==> INFO: Drush 8.4.9-dev re-installation required
BOA [09:27:47] ==> INFO: Drush 10.4.3 re-installation required
BOA [09:27:51] ==> INFO: Drush 10.4.3 setup complete
BOA [09:27:51] ==> INFO: Running system packages update...
BOA [09:28:24] ==> INFO: Installing required libraries and tools, please wait...
BOA [09:29:22] ==> INFO: Installing Percona...
BOA [09:29:30] ==> INFO: Retrieving 8507EFA5 key..
BOA [09:29:35] ==> INFO: Retrieving 8507EFA5 key..
BOA [09:29:39] ==> INFO: Retrieving 8507EFA5 key..
BOA [09:29:42] ==> INFO: Retrieving 8507EFA5 key..
BOA [09:29:46] ==> INFO: Retrieving 8507EFA5 key..
BOA [09:29:49] ==> INFO: Retrieving 8507EFA5 key..
```

**Comment by jcandan** [comment] 2021-08-10 22:29
Docs do say to have DNS set up. I wonder if on my first attempt I hadn't let that finish propagating, and on this second attempt that seems to be working (still in progress, but past the Retrieving key bit) it was finished.

**Comment by omega8cc** [comment] 2021-08-10 22:34
This has been fixed earlier today. Should no longer cause problems with Percona keys loop.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Juc1** [comment] 2021-08-11 11:00
@omega8cc yes the install works ok today, thank you.

**Comment by jcandan** [comment] 2021-08-11 19:08
Not 

Getting the following:

```
ERROR: I can not find PHP-CLI anywhere!
```

Steps to reproduce:

Fresh Digital Ocean basic Debian 9 droplet.

```
root@###:~# cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
root@###:~# boa in-head public mytest.mydomain.com xxxxxxx@gmail.com o1
root@###:~# reboot
...
server:~# barracuda up-head
ERROR: I can not find PHP-CLI anywhere!
server:~# which php
server:~#
```

Variations tried include specifying a PHP version, `boa in-head public mytest.mydomain.com xxxxxxx@gmail.com o1 php-7.4` and trying `baracude up-head`.

**Comment by Juc1** [comment] 2021-08-11 21:13
@jcandan that sounds like a different issue, It is mentioned here https://github.com/omega8cc/boa/issues/1567

My install worked ok. I could post the putty log tomorrow...

**Comment by jcandan** [comment] 2021-08-12 00:10
I debated listing this there, but that was closed as the OP simply missed a step.

I cannot seem to get around this. @omega8cc, would you like this in a new issue?

**Comment by jcandan** [comment] 2021-08-15 00:05
Here's the full stdout from the `boa` command, with line numbers for easier reference. Some data, like email and ip address, redacted.

```
  1 04:45:14jcandan:~ $ ssh root@123.45.67.89
  2 Linux debian-s-1vcpu-1gb-abc1-23 4.9.0-15-amd64 #1 SMP Debian 4.9.258-1 (2021-03-08) x86_64
  3 
  4 The programs included with the Debian GNU/Linux system are free software;
  5 the exact distribution terms for each program are described in the
  6 individual files in /usr/share/doc/*/copyright.
  7 
  8 Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
  9 permitted by applicable law.
 10 root@debian-s-1vcpu-1gb-abc1-23:~# cd;wget -q -U iCab http://files.aegir.cc/BOA.sh.txt;bash BOA.sh.txt
 11 
 12 BOA Meta Installer setup completed
 13 Please check INSTALL.txt and UPGRADE.txt at http://bit.ly/boa-docs
 14 Bye
 15 
 16 
 17 The system is ready for BOA installation!
 18 
 19 We will start screen session for you in 15 seconds
 20 to avoid problems with dropped SSH connections
 21 during BOA stack installation, which may take up to
 22 30-60 minutes, depending on your server speed.
 23 
 24 If your connection will drop, simply log in again
 25 and re-attach your session with 'screen -R' command.
 26 
 27 Please wait a moment until this message disappears.
 28 
 29 Enjoy!
 30 
 31 
 32 root@debian-s-1vcpu-1gb-abc1-23:~# boa in-head public server.thisismyawesomedomainandyoucanthave.one jcandan@example.com o1
 33 
 34 BOA [21:47:56] ==> Skynet Agent v.BOA-4.1.4-dev welcomes you aboard!
 35 
 36 BOA [21:47:59] ==> INFO: NORMAL INIT
 37 BOA [21:47:59] ==> INFO: Public Setup Mode Active
 38 BOA [21:47:59] ==> INFO: Creating your /root/.barracuda.cnf config file
 39 BOA [21:48:12] ==> VIRT: This system is supported: Linux KVM guest
 40 
 41 BOA [21:48:12] ==> Aegir on debian-s-1vcpu-1gb-abc1-23 Debian/stretch x86_64 PHP 7.4
 42 
 43 BOA [21:48:13] ==> INFO: Installing some basic tools now, please wait...
 44 BOA [21:48:31] ==> INFO: Installing sysvinit-core on Debian stretch...
 45 
 46 BOA [21:48:46] ==> NOTE: Please reboot and run 'barracuda up-head system'
 47 BOA [21:48:46] ==> NOTE: after boa completes initial installation
 48 BOA [21:48:46] ==> NOTE: in order to remove unused systemd packages!
 49 
 50 BOA [21:49:05] ==> INFO: Installing more basic tools now, please wait...
 51 BOA [21:49:47] ==> INFO: DNS test: OK
 52 
 53 BOA [21:49:47] ==> INSTALL START -> checkpoint: 
 54 
 55     * Your email address is jcandan@example.com 
 56     * Your IP address is 123.45.67.89 
 57     * Your hostname is server.thisismyawesomedomainandyoucanthave.one
 58 
 59 BOA [21:49:47] ==> INFO: Installing supported Drush versions...
 60 BOA [21:49:47] ==> INFO: Drush 8.4.9-dev re-installation required
 61 BOA [21:49:48] ==> INFO: Drush 10.4.3 re-installation required
 62 BOA [21:49:55] ==> INFO: Drush 10.4.3 setup complete
 63 BOA [21:49:55] ==> INFO: Running system packages update...
 64 BOA [21:50:53] ==> INFO: Installing required libraries and tools, please wait...
 65 BOA [21:52:56] ==> INFO: Installing Percona...
 66 BOA [21:53:15] ==> INFO: Retrieving 8507EFA5 key..
 67 BOA [21:53:42] ==> INFO: Installing Percona 5.7 in Debian/stretch
 68 BOA [21:56:39] ==> INFO: Building MyTop from sources, please wait...
 69 BOA [21:56:44] ==> INFO: Running Percona tables fix, check and upgrade...
 70 BOA [21:56:50] ==> INFO: Generating random password for Percona
 71 BOA [21:56:51] ==> INFO: New Percona root password in /root/.my.pass.txt
 72 BOA [21:56:51] ==> INFO: Percona final setup
 73 BOA [21:56:51] ==> INFO: Restarting Percona server...
 74 BOA [21:56:51] ==> INFO: Percona setup completed
 75 BOA [21:56:51] ==> INFO: You can now log in as root by typing just 'mysql'
 76 BOA [21:56:51] ==> INFO: Running aptitude full-upgrade...
 77 BOA [22:00:06] ==> INFO: Installed Nginx version nginx/1.10.3, upgrade required
 78 BOA [22:00:07] ==> INFO: Installing Nginx...
 79 BOA [22:06:53] ==> INFO: Installing MySecureShell master-20-03-2015...
 80 BOA [22:07:28] ==> INFO: Installing wkhtmltox tools v.0.12.5-1...
 81 BOA [22:07:43] ==> INFO: The wkhtmltox tools v.0.12.5-1 installation complete
 82 BOA [22:07:43] ==> INFO: Fix #1 for libs in Debian stretch
 83 BOA [22:07:43] ==> INFO: Fix #2 for libs in Debian stretch
 84 BOA [22:07:44] ==> INFO: Installing VnStat monitor...
 85 BOA [22:08:10] ==> INFO: Installing a few more tools...
 86 BOA [22:08:10] ==> INFO: Installed MyQuick line for not (5.7.34), rebuild required
 87 BOA [22:08:10] ==> INFO: Building MyQuick 0.10.5 from sources, please wait...
 88 BOA [22:08:44] ==> INFO: Installed MyQuick version line, upgrade required
 89 BOA [22:08:44] ==> INFO: Building MyQuick 0.10.5 from sources, please wait...
 90 BOA [22:09:00] ==> INFO: PHP 7.3.29 will be installed now
 91 BOA [22:09:00] ==> INFO: Building PHP 7.3.29 from sources, please wait...
 92 BOA [22:09:14] ==> INFO: Building PHP 7.3.29 part 1/3
 93 BOA [22:09:20] ==> INFO: Building PHP 7.3.29 part 2/3
 94 BOA [22:11:10] ==> INFO: Building PHP 7.3.29 part 3/3
 95 BOA [22:21:17] ==> WARN: Building PHP 7.3.29 failed!
 96 BOA [22:21:17] ==> INFO: PHP 7.4.21 will be installed now
 97 BOA [22:21:17] ==> INFO: Building PHP 7.4.21 from sources, please wait...
 98 BOA [22:21:32] ==> INFO: Building PHP 7.4.21 part 1/3
 99 BOA [22:21:37] ==> INFO: Building PHP 7.4.21 part 2/3
100 BOA [22:23:15] ==> INFO: Building PHP 7.4.21 part 3/3
101 BOA [22:31:41] ==> WARN: Building PHP 7.4.21 failed!
102 BOA [22:31:41] ==> WAIT: I can not find PHP-CLI anywhere!
103 /opt/tmp/boa/lib/functions/php.sh.inc: line 2307: php: command not found
104 BOA [22:31:41] ==> INFO: PHP rebuild required to fix freetype support...
105 BOA [22:31:42] ==> INFO: Installing Limited Shell 0.9.18.9...
106 BOA [22:31:57] ==> INFO: Installing Redis update for Debian/stretch...
107 BOA [22:35:25] ==> INFO: Installing Aegir Master Instance, please wait...
108 BOA [22:35:26] ==> INFO: Percona is listening on 123.45.67.89.
109 BOA [22:35:48] ==> FATAL ERROR: AegirSetupM installer failed
110 BOA [22:35:48] ==> FATAL ERROR: Aborting Barracuda installer NOW!
111 BOA [22:35:48] ==> HINT: Please check /var/aegir/install.log
112 BOA [22:35:48] ==> HINT: for more information on errors occured
113 
114 BOA [22:36:06] ==> Skynet Agent v.BOA-4.1.4-dev welcomes you aboard!
115 
116 BOA [22:36:09] ==> ERROR: This octopus installer can be used only when the same version
117 BOA [22:36:09] ==> of boa or barracuda installer was used before. Your system must be
118 BOA [22:36:09] ==> upgraded with barracuda installer version BOA-4.1.4-dev first
119 BOA [22:36:09] ==> Bye
120 
121 BOA in-head completed
122 Bye
123 
124 root@debian-s-1vcpu-1gb-abc1-23:~# exit
```

I see problems on line 101 indicating `I can not find PHP-CLI anywhere!`, and line 116, `Your system must be upgraded with barracuda installer version BOA-4.1.4-dev`, even though `Skynet Agent v.BOA-4.1.4-dev welcomes you aboard!`.

**Comment by omega8cc** [comment] 2021-08-15 09:34
@jcandan It’s not related here and typically means you have too little RAM/CPU. Please open new issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2021-08-15 09:35 UTC
Labels: type - bug report, status - fixed

**Comment by jcandan** [comment] 2021-08-15 20:57
Yep. It was RAM, as stated in #1549 too. RTFM fail on my part. See README.md for requirements, folks. :) Things like DNS matter too because Let's Encrypt requires that to be setup.
