### ISSUE TITLE
[nginx] $main_site_name missing from vhost when redirecting to non-install url and with encryption disabled

### ISSUE THREAD

**Issue by pricejn2** [omega8cc/boa#1481] opened 2020-04-23 01:08 UTC
Install url: example.com
Redirect all domain aliases to: www.example.com

I am running latest BOA-4.0.2-dev and any site that redirects to non-install url leads to www.example.com/files/* 404 errors. The `$main_site_name` variable is missing from vhosts that redirect to a non-install url. 

Here is a vhost (in it's entirety) from a site I have that experiencing this issue:

```
# alias redirection virtual host
server {
  listen        *:80;
  #listen       [::]:80;
  server_name  example.com;
  access_log   off;

  ###
  ### Allow access to letsencrypt.org ACME challenges directory.
  ###
  location ^~ /.well-known/acme-challenge {
    alias /data/disk/o2/tools/le/.acme-challenges;
    try_files $uri 404;
  }

  return 301 $scheme://www.example.com$request_uri;
}

server {
  listen        *:80;
  #listen        [::]:80;
  server_name   www.example.com;
  root          /data/disk/o2/static/varbase_bsc-8.8.3-8.8.2/docroot;
  # Extra configuration from modules:

  ###
  ### Allow access to letsencrypt.org ACME challenges directory.
  ###
  location ^~ /.well-known/acme-challenge {
    alias /data/disk/o2/tools/le/.acme-challenges;
    try_files $uri 404;
  }

  include       /data/disk/o2/config/includes/nginx_vhost_common.conf;
}
```

A normal vhost would also have `fastcgi_param MAIN_SITE_NAME example.com;` and `set $main_site_name "example.com";`

related to #457

**Comment by pricejn2** [comment] 2020-04-23 01:09
Seems like this stopped working within the last 3-4 months. Sites that haven't been verified for some time still have the proper vhost but newly verified or newly created sites are incorrect as shown above.

**Comment by pricejn2** [comment] 2020-04-23 01:19
This appears to only be happening for sites with encryption disabled. One workaround appears to enable encryption.

**Comment by omega8cc** [comment] 2020-04-23 02:42
This looks like regression we have fixed only in ssl templates: https://github.com/omega8cc/provision/commit/566c12c8ce6736bdf460f2b1676d0795d7f47f35

Now fixed also in non-ssl: https://github.com/omega8cc/provision/commit/8757537f42cfbbdf77fca395cddd043f803efd04

**Closed** 2020-04-23 02:57 UTC
Labels: area - provision, status - fixed, type - bug report

**Comment by pricejn2** [comment] 2020-04-23 12:46
Thank you very much for the quick patch!
