### ISSUE TITLE
login as o1.ftp fails

### ISSUE THREAD

**Issue by Amstercad** [omega8cc/boa#1557] opened 2021-02-14 17:32 UTC
Steps to reproduce:

1. - Install a new BOA server
2. - Receive the email titled: "Your Aegir Install on {today's date/time} [o1]"
3. - These instructions do not work currently:

> ----------------------------------------
> #3. ADDING MODULES & THEMES
> ----------------------------------------
> 
> To add modules/themes to any of the enabled platforms,
> you need to log into your FTPS/SSH/SFTP account:
> 
>   host: o1.subdomain.example.com
>   user: o1.ftp
>   pass: PASSWORD
>   port: 21 (for FTPS connections)
>   port: 22 (for SSH and SFTP connections)

After much testing, this error message is consistent:

`user@example-server:~/websites$ ssh o1.ftp@subdomain.example.com`
`The authenticity of host 'subdomain.example.com (12.34.56.78)' can't be established.`
`ECDSA key fingerprint is SHA256:Gzu5wrz+jHNsfgzdfh+JezesSAhGtmjFsKlx0eTab0.`
`Are you sure you want to continue connecting (yes/no)? yes`
`Warning: Permanently added 'subdomain.example.com,12.34.56.78' (ECDSA) to the list of known hosts.`
`o1.ftp@subdomain.example.com: Permission denied (publickey).`

The root login using a public key works fine, and I can use root successfully to do this:
`su o1.ftp`

And what I am really trying to do is:
`npm install gulp`   (as either `o1` or `o1.ftp` user)
...but I can't get that to work at all currently. Maybe this detail deserves a separate ticket, once I get so far.

Actually `npm install gulp` looks like it's working 100%:

`+ gulp@4.0.2
updated 1 package and audited 649 packages in 10.337s`

However when I try something like `gulp compile` here's my output"

`o1.ftp:[xxx_subtheme]$ gulp compile`
`/bin/dash: 1: gulp: not found`

**Comment by maninder007** [comment] 2021-03-01 10:15
Same issue is happening when I am Installing the latest boa on digitalocean droplet. The root login through public key method using Bitvise client works fine, But logging in by 01.ftp user (Port 22), through Initial method password takes me to public key method and login is refused.

**Comment by omega8cc** [comment] 2021-04-11 03:04
Only restricted shell user can use rvm/npm -- please follow the docs: https://github.com/omega8cc/boa/blob/master/docs/RVM.txt

We can't reproduce the issue with SSH access for restricted shell user.

Are you running BOA head or stable?

Remember, contributions to this repository should follow its contributing guidelines: https://github.com/omega8cc/boa/blob/83a5efc83ff042d178be064e57f5c38d1ee619e4/CONTRIBUTING.txt

You could disable password based SSH access with `/root/.ssh.auth.keys.only.cnf` empty file, but it's not default mode, because otherwise regular users couldn't access their accounts to add SSH keys.

**Comment by omega8cc** [comment] 2023-05-08 18:51
Closing old tickets related to issues fixed already. Feel free to reopen if something is still relevant. Thank you!

**Closed by omega8cc** 2023-05-08 18:51 UTC
