### ISSUE TITLE
Compatibility of Aegir Saas module

### ISSUE THREAD

**Issue by Corvalan** [omega8cc/boa#1257] opened 2018-02-24 03:33 UTC
Has the Aegir Saas module already been tested with the BOA installation?
[https://www.drupal.org/project/hosting_services](https://www.drupal.org/project/hosting_services)

```
=======================
Aims to be a one-stop shop for all Web services functionality offered within the Aegir Hosting System. 
It allows for remote site management via the Services framework.

The following modules are included in the suite:

Aegir Services API (the base module)
Aegir Services Example REST Endpoint
Aegir Services Example Client
Aegir SaaS
The Aegir SaaS sub-module sets up a fully functional endpoint (via the Aegir Services API) 
allowing for remote administration of sites, notably creating new ones, for software-as-a-service (SaaS) 
/ site-factory Aegir set-ups. It fully configures a service endpoint providing common parameters 
for site creation as configured in the module's settings. Using the API's task resource, sites can 
also be disabled, enabled, deleted, and have any other task performed on them supported by 
your Aegir installation. 
```

**Comment by omega8cc** [comment] 2018-02-25 17:55
It's a duplicate of the issue you have opened last year.. #1177

**Closed by omega8cc** 2018-02-25 17:55 UTC
