### ISSUE TITLE
D7 platforms not installing new distro at all - 4.1.3 stable

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#1524] opened 2020-09-26 12:39 UTC
On new 4.1.3 stable, D7 platforms still do not install properly (I had them listed in the .o3octopus.cnf file, AND in the 
/data/disk/o3/static/control/platforms.info file.  Is this perhaps the origin of this problem)?

Could you answer this question, whether we should list the platforms to install only in the platforms.info file, or only in the octopus .cnf file, or in both, please?

I cannot resolve this because of issue # 1523 - inability to force the octopus upgrade.

gist of platform verify error is here:

https://gist.github.com/EdNett/4291ea872e42a1ac0ea139bc4198953b

The distro/047 that the gist error refers to does not exist - it was never created. 

My .o3.octopus.cnf file had the following settings:

_HOT_SAUCE=YES
_USE_CURRENT=NO
_DEL_OLD_EMPTY_PLATFORMS=2
_DEL_OLD_BACKUPS=45
_DEL_OLD_TMP=2
_LOCAL_NETWORK_IP=
_PHP_FPM_VERSION=7.4
_PHP_CLI_VERSION=7.3

Regards,

Ed

**Comment by omega8cc** [comment] 2020-09-27 12:32
It's a duplicate of #1522

**Closed by omega8cc** 2020-09-27 12:32 UTC
