### ISSUE TITLE
Dns not resolving

### ISSUE THREAD

**Issue by timlie** [omega8cc/boa#610] opened 2015-02-09 07:36 UTC
I noticed on 2 of my servers that the DNS was not resolving anymore.
On the first server this happened a week or 2 ago (probably after an barracuda up-stable system update). This server was on boa-2.3.8.
After reading this topic:
https://github.com/omega8cc/boa/issues/549
i checked these files.
In the file /etc/pdnsd.conf there where no google servers anymore.
It justed stated:

server {
        timeout=100;      // By default 50.
        interval=5m;      // Test every 5 minutes.
        uptest=ping;
        ping_timeout=300; // By default 30 seconds.
        purge_cache=off;
        exclude=.local.;
}

instead of:

server {
        label = "google-servers";
        ip=8.8.8.8;
        ip=8.8.4.4;
        timeout=100;      // By default 50.
        interval=5m;      // Test every 5 minutes.
        uptest=ping;
        ping_timeout=300; // By default 30 seconds.
        purge_cache=off;
        exclude=.local.;
}

Yesterday i upgraded a server to boa-v2.4.0 and also on this server these lines disappeared.

Tried to run:

    rm -f /etc/resolv.conf
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    echo "nameserver 8.8.4.4" >> /etc/resolv.conf

And then another upgrade from barracuda, but this did not help.
Had to change it manually again.

It seems like it is not boa version specific because first server was first on boa-2.3.8.
Servers are both Ubuntu 12.04

Thanks!

**Comment by ar-jan** [comment] 2015-02-09 12:14
Perhaps related: I noticed when doing a clean install of BOA 2.4.0 (on Debian 7) that the install log in /var/backups ended with the same message about pdnsd not installing/running correctly.

But this time after I rebooted pdnsd did start/restart, so I suppose it's not the same as last time. If that's likely related I still have the logs.

**Comment by omega8cc** [comment] 2015-02-09 12:29
Please follow guidelines: https://github.com/omega8cc/boa/blob/master/CONTRIBUTING.txt

**Comment by timlie** [comment] 2015-02-09 12:30
hmm, this file /etc/pdnsd.conf seems also to get overridden so now they are again gone...
I'm back at:

<code>
server {
timeout=100; // By default 50.
interval=5m; // Test every 5 minutes.
uptest=ping;
ping_timeout=300; // By default 30 seconds.
purge_cache=off;
exclude=.local.;
}
</code>

**Comment by timlie** [comment] 2015-02-09 12:48
Sorry.
Here are my logs and config.

https://gist.github.com/timlie/2240c710c47b8c99444e

**Comment by timlie** [comment] 2015-02-09 13:56
And this is the pdnsd.conf file:

https://gist.github.com/timlie/879103ff74c0df160714

**Comment by timlie** [comment] 2015-02-10 07:37
And this is probably a much more detailed log:

https://gist.github.com/timlie/fd07ba88acc794a6aa17

**Comment by macmladen** [comment] 2015-02-10 16:37
I must say that I experienced the same, suddenly my VPS has lost the ability to resolve so that `barracuda up-stable` failed to complete as it lost ability to download anything. I do admit that it could be that I had incomplete upgrade due to ssh connection loss.

I didn't realized at first as server was operational so I left it but later I had to resolve and while searching I found this. I added servers but it didn't work so I rebooted and then **again** tried to `barracuda up-stable`.

Now, Skynet agent identified itself as 2.4.0 so probably first run did make something or some other run, not sure. The procedure did take quite some time, building new PHP. It also did **rebuild** `DNS cache pdnsd server re-installation forced` and when it finished it was **unable** to `ping google.com`. After reboot, everything was normal.

Steps to reproduce problem (I did that just now and it happened again):
```
$ ping google.com    # work as expected
PING google.com (173.194.65.113) 56(84) bytes of data.
64 bytes from ee-in-f113.1e100.net (173.194.65.113): icmp_req=1 ttl=51 time=4.08 ms
64 bytes from ee-in-f113.1e100.net (173.194.65.113): icmp_req=2 ttl=51 time=4.21 ms
64 bytes from ee-in-f113.1e100.net (173.194.65.113): icmp_req=3 ttl=51 time=4.19 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 4.085/4.162/4.213/0.093 ms

$ barracuda up-stable
.....
BARRACUDA upgrade completed
Bye

$ ping google.com
ping: unknown host google.com

$ reboot ; exit
....
$ ping google.com    # works again after reboot
PING google.com (173.194.65.101) 56(84) bytes of data.
64 bytes from ee-in-f101.1e100.net (173.194.65.101): icmp_req=1 ttl=51 time=23.4 ms
64 bytes from ee-in-f101.1e100.net (173.194.65.101): icmp_req=2 ttl=51 time=23.8 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 23.490/23.655/23.821/0.225 ms
```

**Comment by omega8cc** [comment] 2015-02-10 17:02
@macmladen LOGS, please.

**Comment by omega8cc** [comment] 2015-02-10 17:06
That said, we couldn't reproduce this on any Debian nor Ubuntu instance we host or manage remotely, so it seem not distro specific issues.

What are your hosts, guys?

**Comment by omega8cc** [comment] 2015-02-10 17:10
Do you have `/root/.use.local.nameservers.cnf` file, perhaps?

Also, what you have in the `/root/.local.dns.IP.list` file, if it exists?

**Comment by timlie** [comment] 2015-02-10 17:24
I'm hosting on Digital Ocean.

File /root/.use.local.nameservers.cnf does exist but is empty.
File /root/.local.dns.IP.list does exist too and contains:

label = "google-servers";
        ip=8.8.4.4;
        ip=8.8.8.8;

**Comment by omega8cc** [comment] 2015-02-10 17:45
Please check when the file has been crated with:

ls -ls /root/.use.local.nameservers.cnf

Then delete it and rename also /var/backups/resolv.conf.vanilla to some other name.

Then try to run barracuda upgrade again.

**Comment by pricejn2** [comment] 2015-02-10 18:15
For me, when ```find_correct_ip()``` returns nothing, I clear pdnsd cache using ```pdnsd-ctl empty-cache```.  

There are multiple places throughout BOA that use ```rm -f /var/cache/pdnsd/pdnsd.cache``` instead of  built in ```pdnsd-ctl empty-cache```.

**Comment by timlie** [comment] 2015-02-10 18:20
Thanks a lot!!! Both of my servers are resolving again!

This was the result for ls -ls /root/.use.local.nameservers.cnf:
root 0 Nov 24 19:03 /root/.use.local.nameservers.cnf

This was the result from my second server for ls -ls /root/.use.local.nameservers.cnf:
root 0 Jan 29 11:03 /root/.use.local.nameservers.cnf

After making the upgrade again, dns is fine now!

Don't know how this dns problem happened but thanks a lot guys for your great support (as always)!

**Comment by santo74** [comment] 2015-02-11 08:32
I had the same issue as well.
After following the advices above I finally got through the upgrade process.
Thanks for that!

However, while after reboot everything is working fine, after some time dns resolving stops working
After some investigation it appears that it always starts at 3 minutes past the hour.
At that time I see this in the syslog:
```
Feb 11 08:03:01 webmaster01 /USR/SBIN/CRON[17226]: (root) CMD (bash /var/xdrago/second.sh >/dev/null 2>&1)
Feb 11 08:03:01 webmaster01 /USR/SBIN/CRON[17227]: (root) CMD (bash /var/xdrago/minute.sh >/dev/null 2>&1)
Feb 11 08:03:01 webmaster01 /USR/SBIN/CRON[17228]: (root) CMD (bash /var/xdrago/runner.sh >/dev/null 2>&1)
Feb 11 08:03:01 webmaster01 /USR/SBIN/CRON[17229]: (root) CMD (bash /var/xdrago/manage_ltd_users.sh >/dev/null 2>&1)
Feb 11 08:03:01 webmaster01 /USR/SBIN/CRON[17231]: (aegir) CMD (/usr/bin/env php /var/aegir/drush/drush.php '@hostmaster' hosting-dispatch >/dev/null 2>&1)
Feb 11 08:03:01 webmaster01 /USR/SBIN/CRON[17232]: (root) CMD (bash /var/xdrago/clear.sh >/dev/null 2>&1)
Feb 11 08:03:01 webmaster01 /USR/SBIN/CRON[17238]: (root) CMD (   bash /var/xdrago/guest-fire.sh >/dev/null 2>&1)
Feb 11 08:03:02 webmaster01 pdnsd[2672]: Caught signal 15. Exiting.
Feb 11 08:03:04 webmaster01 pdnsd[18274]: pdnsd-1.2.8-par starting.
Feb 11 08:03:04 webmaster01 pdnsd[18274]: Cache file /var/cache/pdnsd/pdnsd.cache ignored because of incompatible version identifier
```

This is an ls of the cache file before:
```
webmaster01:~# ls -lF /var/cache/pdnsd/pdnsd.cache
-rw------- 1 pdnsd proxy 1.2K Feb 11 08:59 /var/cache/pdnsd/pdnsd.cache
```
And this is an ls of the cache file after:
```
webmaster01:~# ls -lF /var/cache/pdnsd/pdnsd.cache
-rw-r--r-- 1 pdnsd proxy 4 Feb 11 09:03 /var/cache/pdnsd/pdnsd.cache
```

So it seems the dns cache file gets corrupted by the cronjob

**Comment by Pls** [comment] 2015-02-11 09:52
Checked my syslog, and can confirm I am getting same exact psdnd cache error.

**Comment by santo74** [comment] 2015-02-11 10:20
As a test I disabled the clear.sh cron job and I didn't have any problems anymore related to dns resolving:
```
#03 * * * * bash /var/xdrago/clear.sh >/dev/null 2>&1
```

**Comment by macmladen** [comment] 2015-02-11 10:34
**[Debian 7]**
I can definitely confirm that 3 minutes past hour, server stopped resolving.

```
root ~ 08:50:54 # ping apple.com
PING apple.com (17.172.224.47) 56(84) bytes of data.

root ~ 09:01:43 # ping google.com
ping: unknown host google.com
```

Reboot helps as after rebooting it resolves.

* `pdnsd-ctl empty-cache` does not help.
* `service pdnsd restart` also does not help.
* copying back previously working `/var/cache/pdnsd/pdnsd.cache` also does not help.

```
root ~ 09:26:57 # ls -ls /root/.use.local.nameservers.cnf
0 -rw-r--r-- 1 root root 0 Nov 28 13:03 /root/.use.local.nameservers.cnf

root ~ 09:28:01 # cat .local.dns.IP.list 
        label = "google-servers";
        ip=4.2.2.2;
        ip=8.8.4.4;
        ip=8.8.8.8;
```

Now in order to find how to restart it, I've made status dump like `service pdnsd status > pdnsd.status` on working and non working to notice the difference:

```
root ~ 10:12:58 # diff pdnsd.status pdnsd.status.n 
  ...
77c77
< 	server assumed available: yes
---
> 	server assumed available: no
```

So solution is to have it up again, 

```
root ~ 10:12:54 # ping google.com
ping: unknown host google.com

root ~ 10:24:30 # pdnsd-ctl server 1 up
Opening socket /var/cache/pdnsd/pdnsd.status
Succeeded

root ~ 10:26:50 # ping google.com
PING google.com (173.194.65.113) 56(84) bytes of data.
```

**Comment by omega8cc** [comment] 2015-02-11 18:12
Hmm.. thanks for the investigation. We need to find a way to reproduce this, though.

**Comment by macmladen** [comment] 2015-02-12 09:14
I've checked into
```
#03 * * * * bash /var/xdrago/clear.sh >/dev/null 2>&1
```
and discovered that by commenting these lines, dns continues to work (@87 near the end of file):
```
#if [ -e "/etc/resolvconf/run/interface/lo.pdnsd" ]; then
#  rm -f /etc/resolvconf/run/interface/eth*
#  resolvconf -u &> /dev/null
#fi
```
so it is either `rm` or `resolvconf -u` that are making trouble.

**Comment by omega8cc** [comment] 2015-02-13 16:06
Could you post the result of

`ls -la /etc/resolvconf/run/interface/*`

and then the contents of each file listed?

**Comment by macmladen** [comment] 2015-02-13 16:11
There are two files:
```
root ~ 16:09:21 # cat /etc/resolvconf/run/interface/lo.pdnsd 
nameserver 127.0.0.1

root ~ 16:09:53 # cat /etc/resolvconf/run/interface/eth0.inet 
nameserver 8.8.4.4
```

**Comment by omega8cc** [comment] 2015-02-13 16:15
Hmm, two questions then:

1. Why do you have the line `ip=4.2.2.2;` in `.local.dns.IP.list`?
2. Why do you have the `interface/eth0.inet` file?

None of those things are managed/expected by BOA and `interface/eth*` is removed to avoid conflicts with `interface/lo.pdnsd`

**Comment by omega8cc** [comment] 2015-02-13 16:18
When averaging runs fine, what is the result of command:

`dig omega8.cc`

**Comment by macmladen** [comment] 2015-02-13 16:25
I really didn't change anything manually at any time, really. My system was setup first with **2.0.9** as **head** at first but then changed to **stable** and have only done `barracuda up-stable`. There were few hiccups along the road, but never changed those files (nor added system things like that `eth0.inet` file)
```
root ~ 16:13:25 # dig omega8.cc

; <<>> DiG 9.8.4-rpz2+rl005.12-P1 <<>> omega8.cc
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25634
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;omega8.cc.			IN	A

;; ANSWER SECTION:
omega8.cc.		900	IN	A	72.251.241.251

;; Query time: 124 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Feb 13 16:20:34 2015
;; MSG SIZE  rcvd: 43
```

**Closed** 2015-02-13 16:54 UTC
Labels: status - needs work, type - bug report

**Comment by omega8cc** [comment] 2015-02-13 16:56
Two things could play role here:

1, Race conditions between two maintenance scripts
2. Incorrect pdnsd restarts procedure in many places.

**Comment by omega8cc** [comment] 2015-02-13 16:58
We will apply as many fixes as possible also to stable, so it should be fixed for everyone, unless you have disabled updates with `_SKYNET_MODE=OFF`
