### ISSUE TITLE
Random Redis/fpm restarts

### ISSUE THREAD

**Issue by namontague** [omega8cc/boa#1695] opened 2023-02-28 04:57 UTC
Hi,

We have been noticing random restarts of redis. 
I believe this might be due to an oversight in the below script.
https://github.com/omega8cc/boa/blob/master/aegir/tools/system/minute.sh

Function : redis_slow_check

There is no timeframe in the condition, just the last 500 lines are checked for "PhpRedis.php".
We have a slow log every now and then, so after every 6th slow log we see redis and fpm restart.

The 6 logs could take 3 days or 3 weeks and the redis_slow_check function see's this as a slow incident.
Is this correct behaviour?

**Comment by omega8cc** [comment] 2023-04-27 22:52
This works as designed and moves all php logs away to /var/backups/php-logs/ once the locked/slow Redis is detected, so it will not keep restarting Redis because the error is still there, only because the new error appeared again.

Please review the archived logs in /var/backups/php-logs/ to debug this further, since slow Redis is a sign of either system or website serious issue, which should be fixed.

Also, make sure to keep your system up to date with `barracuda up-head system`.

**Closed** 2023-04-27 22:53 UTC
Labels: status - by design
