### ISSUE TITLE
Feb 28 head upgrade (2.4.1-dev) leaves master hostmaster site offline - IPv6 problem, I believe

### ISSUE THREAD

**Issue by EdNett** [omega8cc/boa#635] opened 2015-02-28 16:09 UTC
This error keeps repeating for me, thus I am upgrading a 2.4.0 stable server whose master site has been offline since the upgrade from 2.3.9, and it is still offline. I may have found the problem - it is taking an IPv6 address from the server (which has both an ipv6 and an ipv4 address), and is not stating it correctly as can be seen in the following up-head error report (don't there need to be 8 placeholders, so at least two more ":"'s - with or without the zeros in an ipv6 address?):

(Of course, the real question is probably: Why isn't the upgrade script trying to connect to the master barracuda site at localhost?)

Platforms path /var/aegir/platforms is writable. [1.83 sec, 7.55 MB]            [success]
Drush bootstrap phase : _drush_bootstrap_drupal_configuration() [1.83 sec, 7.55 [bootstrap]
MB]
sql-query: SELECT 1; [1.84 sec, 7.71 MB]                                        [status]
Executing: mysql --defaults-extra-file=/var/aegir/.tmp/drush_uDYkJx --database=masterserver
1tou --host=server1.example.com --port=3306 --silent  < /var/aegir/.tmp/drush_KwgnID
  ERROR 1130 (HY000): Host '2863:69d0:32:a00::519' is not allowed to connect to this MariaD
B server
Drush was not able to start (bootstrap) the Drupal database.                    [error]

Logs to uploaded now.

**Comment by EdNett** [comment] 2015-02-28 16:27
barracuda cnf file is here:  https://gist.github.com/EdNett/cc543f4fa7932e8a6615

barracuda-log-txt is here:  https://gist.github.com/EdNett/7def93f25c979a82ffc2

The contents of my /etc/hosts file (sanitized) is interesting (I guess the IPv6 the upgrade script is writing to the terminal and thus using, simply erases all zeros, so maybe this is not the problem?:

127.0.0.1 localhost
valid-I-P-v4 server1.example.com server1
2863:69d0:0032:0a00:0000:0000:0000:0519 server1.example.com server1
::1             localhost ip6-localhost ip6-loopback
fe00::0         ip6-localnet
ff00::0         ip6-mcastprefix
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

**Comment by omega8cc** [comment] 2015-03-02 20:25
It is in fact a duplicate of https://www.drupal.org/node/2241805

The answer is still the same, though. Please remove any ipv6 entries from your /etc/hosts to avoid such problems, because it will not be used anyway and will break things in an unexpected ways.

**Closed by omega8cc** 2015-03-02 20:25 UTC
