### ISSUE TITLE
MariaDB 10.1 support (default version)

### ISSUE THREAD

**Issue by macmladen** [omega8cc/boa#866] opened 2016-02-07 12:13 UTC
BOA in 2.4.7 uses Maria 5.5.47 release which is the latest release in 5.5 series.

As BOA 3.0.0 is postponed, maybe it could be considered to include latest MariaDB stable release and that is 10.1.11 released on 2016-01-29?

Maybe I am not aware of potential problems that brings, but it would be nice complement to Drupal 8 / PHP 7.0 upgrade?

**Comment by Pls** [comment] 2016-02-07 13:32
I'm pretty sure that 10.x is supported right now, it is documented here - https://github.com/omega8cc/boa/blob/62b9241630493679067506ee9e0f961b79b9b164/lib/settings/barracuda.sh.cnf#L298

**Comment by macmladen** [comment] 2016-02-07 13:35
True, it is.

Is there any reason why 10.x is not set as default?

**Comment by omega8cc** [comment] 2016-02-10 11:15
Maybe we should switch to MariaDB 10.1 by default in BOA-3.0.0, so we could get rid of the separate Galera 10.0 and MariaDB 10.0 install modes. This could be another reason to release yet another 2.4.x before 3.0.0.

**Comment by macmladen** [comment] 2016-02-10 11:42
I agree.

Probably it would be good idea to have just one big change per release with bug fixes so that big issues do not create complex interaction cases.

**Comment by pricejn2** [comment] 2016-02-10 18:39
+1 for moving to MariaDB 10.x as default database engine

**Comment by attiks** [comment] 2016-05-12 15:49
FYI, there seems to be a 'bug' in MariaDB, see https://www.drupal.org/node/2723605

**Comment by omega8cc** [comment] 2016-05-12 16:48
Thanks @attiks for the heads-up! The newer is not always better, apparently. We didn't even test 10.1 yet. It would be good to test if the problem is only 10.1 specific or maybe it affects also 10.0?

**Comment by colans** [comment] 2016-07-23 17:23
We're got an issue in Aegir core that may be related: [Install fails on MariaDB 10 without password (new default)](https://www.drupal.org/node/2770819).

**Comment by omega8cc** [comment] 2016-07-25 09:49
@colans -- Maybe it's Xenial specific issue? We never experienced any issues with MariaDB 10.0 in BOA, but we use and recommend Debian, while Ubuntu is minimally supported, and we didn't add Xenial support, yet.

**Comment by colans** [comment] 2016-07-25 15:03
Quite possibly.

**Comment by omega8cc** [comment] 2016-08-21 13:45
MariaDB 10.0 will be default version used in BOA-3.2.x, so we could add 10.1 as an option, with caveats on possible issues.

**Comment by omega8cc** [comment] 2016-08-21 13:55
Note that we already force MariaDB 10.0 for a long time on Debian Jessie and Ubuntu Trusty.

**Comment by omega8cc** [comment] 2016-08-21 14:28
OK, so our initial investigation resulted with interesting findings. There are some important changes in MariaDB 10.1 which are not compatible with Aegir (Provision) and also with BOA specific code.

Namely, as listed in [Upgrading from MariaDB 10.0 to 10.1](https://mariadb.com/kb/en/mariadb/upgrading-from-mariadb-100-to-101/) 10.1 enforces `sql_mode` and sets default values which break the way `GRANT` is used in Aegir: `NO_AUTO_CREATE_USER, NO_ENGINE_SUBSTITUTION`

When you check what `NO_AUTO_CREATE_USER` means, [MariaDB docs explain](https://mariadb.com/kb/en/mariadb/grant/) that:

>> If the `NO_AUTO_CREATE_USER` SQL_MODE is set, users can only be created with a `CREATE USER` statement. In this case `GRANT` will produce an error when the specified user does not exist.

Uh oh..

**Comment by omega8cc** [comment] 2016-08-21 14:54
The good news is that BOA already overrides this change with:

`sql_mode = NO_ENGINE_SUBSTITUTION`

But Aegir (vanilla) will have to force this to make it work with 10.1

**Comment by colans** [comment] 2016-08-30 19:42
Has an Aegir core issue been opened for this?  Looks like it's not the same problem as [Install fails on MariaDB 10 without password (new default)](https://www.drupal.org/node/2770819) because Ubuntu 10.04 (xenial) shipped with 10.0, not 10.1.

**Comment by omega8cc** [comment] 2016-08-31 10:53
It was not reported on d.o, I think.

**Comment by colans** [comment] 2016-08-31 15:17
Filed at [New NO_AUTO_CREATE_USER default breaks grants in MariaDB 10.1](https://www.drupal.org/node/2793033).

**Comment by omega8cc** [comment] 2016-09-21 12:09
MariaDB 10.0 is causing problems we didn't see before with 5.5, with random crashes, but so far only on legacy Debian Wheezy systems. We should just switch to 10.1, I think, plus re-introduce Percona support, so we could determine what may cause these problems, if we will be able to compare results.

**Closed** 2016-09-21 12:29 UTC
Labels: status - todo, type - feature request

**Comment by memtkmcc** [comment] 2016-09-21 17:11
10.1 works just fine with BOA.
