### ISSUE TITLE
Advice on _SSL_FROM_SOURCES=YES

### ISSUE THREAD

**Issue by petrowsky** [omega8cc/boa#751] opened 2015-07-17 22:11 UTC
I've been trying to get ssl to update from sources but I think there is some setting missing. Running a barracuda up-stable system with   _SSL_FROM_SOURCES=YES does not update openssl.

I get this.
```
~# apt-mark showhold
openssh-client
openssh-server
ssh
```
Because SSH does indeed update to 6.9, but ssl is still at an older version. Is there some setting I'm missing? Here are some of my .barracuda settings which seem to apply to fix_libssl(). Do I need to have _NGINX_FORWARD_SECRECY=YES in order to get install_ssl_src() to run?

Current settings
  _NGINX_SPDY=YES
  _NGINX_FORWARD_SECRECY=NO
  _SSL_FROM_SOURCES=YES
  _SSH_FROM_SOURCES=YES

It looks like in install_ssl_src() you're looking for it being held. This is my output from dpkg.

```
s1:~# dpkg --get-selections | grep openssl
libcrypt-openssl-random-perl			install
libcurl4-openssl-dev				install
libgnutls-openssl27:amd64			install
openssl						install
```

Should I just set _SSL_FORCE_REINSTALL=YES and call it a day?

**Comment by omega8cc** [comment] 2015-07-17 22:38
If you are on Wheezy, then it is a duplicate of #749

**Closed by omega8cc** 2015-07-17 22:38 UTC
